---
version: 2
archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-proxmoxve
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/muhlba91/pulumi-proxmoxve/provider/pkg/version.Version={{ .Tag }}
    main: ./cmd/pulumi-resource-proxmoxve/
source:
  enabled: true
signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --yes
      - "--bundle=${signature}"
      - "${artifact}"
    artifacts: all
    output: true
sboms:
  - artifacts: archive
  - id: source
    artifacts: source
changelog:
  disable: true
  use: github
  filters:
    exclude:
      - "^docs"
      - "^chore"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bugfixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other Work
      order: 999
release:
  disable: false
  prerelease: auto
snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT"
