// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ProxmoxVE.VM.Inputs
{

    public sealed class ClonedVirtualMachineCdromArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The file ID of the CD-ROM, or `cdrom|none`. Defaults to `None` to leave the CD-ROM empty. Use `Cdrom` to connect to the physical drive.
        /// </summary>
        [Input("fileId")]
        public Input<string>? FileId { get; set; }

        public ClonedVirtualMachineCdromArgs()
        {
        }
        public static new ClonedVirtualMachineCdromArgs Empty => new ClonedVirtualMachineCdromArgs();
    }
}
