// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ProxmoxVE.VM.Outputs
{

    [OutputType]
    public sealed class VirtualMachineVga
    {
        /// <summary>
        /// Enable VNC clipboard by setting to `vnc`. See the [Proxmox documentation](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings) section 10.2.8 for more information.
        /// </summary>
        public readonly string? Clipboard;
        /// <summary>
        /// Whether to enable the VGA device
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// The VGA memory in megabytes (defaults to `16`).
        /// </summary>
        public readonly int? Memory;
        /// <summary>
        /// The VGA type (defaults to `std`).
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private VirtualMachineVga(
            string? clipboard,

            bool? enabled,

            int? memory,

            string? type)
        {
            Clipboard = clipboard;
            Enabled = enabled;
            Memory = memory;
            Type = type;
        }
    }
}
