// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ProxmoxVE.VM.Outputs
{

    [OutputType]
    public sealed class VirtualMachineNetworkDevice
    {
        public readonly string? Bridge;
        public readonly bool? Enabled;
        public readonly string? MacAddress;
        public readonly string? Model;
        public readonly double? RateLimit;
        public readonly int? VlanId;

        [OutputConstructor]
        private VirtualMachineNetworkDevice(
            string? bridge,

            bool? enabled,

            string? macAddress,

            string? model,

            double? rateLimit,

            int? vlanId)
        {
            Bridge = bridge;
            Enabled = enabled;
            MacAddress = macAddress;
            Model = model;
            RateLimit = rateLimit;
            VlanId = vlanId;
        }
    }
}
