// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.muehlbachler.pulumi.proxmoxve.Sdn_fabric_node.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetOpenfabricResult {
    /**
     * @return The unique identifier of the SDN fabric.
     * 
     */
    private String fabricId;
    private String id;
    /**
     * @return Set of interface names associated with the fabric node.
     * 
     */
    private List<String> interfaceNames;
    /**
     * @return IPv4 address for the fabric node.
     * 
     */
    private String ip;
    /**
     * @return IPv6 address for the fabric node.
     * 
     */
    private String ip6;
    /**
     * @return The unique identifier of the SDN fabric node.
     * 
     */
    private String nodeId;

    private GetOpenfabricResult() {}
    /**
     * @return The unique identifier of the SDN fabric.
     * 
     */
    public String fabricId() {
        return this.fabricId;
    }
    public String id() {
        return this.id;
    }
    /**
     * @return Set of interface names associated with the fabric node.
     * 
     */
    public List<String> interfaceNames() {
        return this.interfaceNames;
    }
    /**
     * @return IPv4 address for the fabric node.
     * 
     */
    public String ip() {
        return this.ip;
    }
    /**
     * @return IPv6 address for the fabric node.
     * 
     */
    public String ip6() {
        return this.ip6;
    }
    /**
     * @return The unique identifier of the SDN fabric node.
     * 
     */
    public String nodeId() {
        return this.nodeId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetOpenfabricResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String fabricId;
        private String id;
        private List<String> interfaceNames;
        private String ip;
        private String ip6;
        private String nodeId;
        public Builder() {}
        public Builder(GetOpenfabricResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fabricId = defaults.fabricId;
    	      this.id = defaults.id;
    	      this.interfaceNames = defaults.interfaceNames;
    	      this.ip = defaults.ip;
    	      this.ip6 = defaults.ip6;
    	      this.nodeId = defaults.nodeId;
        }

        @CustomType.Setter
        public Builder fabricId(String fabricId) {
            if (fabricId == null) {
              throw new MissingRequiredPropertyException("GetOpenfabricResult", "fabricId");
            }
            this.fabricId = fabricId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetOpenfabricResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder interfaceNames(List<String> interfaceNames) {
            if (interfaceNames == null) {
              throw new MissingRequiredPropertyException("GetOpenfabricResult", "interfaceNames");
            }
            this.interfaceNames = interfaceNames;
            return this;
        }
        public Builder interfaceNames(String... interfaceNames) {
            return interfaceNames(List.of(interfaceNames));
        }
        @CustomType.Setter
        public Builder ip(String ip) {
            if (ip == null) {
              throw new MissingRequiredPropertyException("GetOpenfabricResult", "ip");
            }
            this.ip = ip;
            return this;
        }
        @CustomType.Setter
        public Builder ip6(String ip6) {
            if (ip6 == null) {
              throw new MissingRequiredPropertyException("GetOpenfabricResult", "ip6");
            }
            this.ip6 = ip6;
            return this;
        }
        @CustomType.Setter
        public Builder nodeId(String nodeId) {
            if (nodeId == null) {
              throw new MissingRequiredPropertyException("GetOpenfabricResult", "nodeId");
            }
            this.nodeId = nodeId;
            return this;
        }
        public GetOpenfabricResult build() {
            final var _resultValue = new GetOpenfabricResult();
            _resultValue.fabricId = fabricId;
            _resultValue.id = id;
            _resultValue.interfaceNames = interfaceNames;
            _resultValue.ip = ip;
            _resultValue.ip6 = ip6;
            _resultValue.nodeId = nodeId;
            return _resultValue;
        }
    }
}
