// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mapping

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-proxmoxve/sdk/v7/go/proxmoxve/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// > **Deprecated:** Use `hardware/mapping.Pci` instead. This resource will be removed in v1.0.
//
// Manages a PCI hardware mapping in a Proxmox VE cluster.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-proxmoxve/sdk/v7/go/proxmoxve/hardware"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := hardware.NewPciLegacy(ctx, "example", &hardware.PciLegacyArgs{
//				Comment: pulumi.String("This is a comment"),
//				Name:    pulumi.String("example"),
//				Maps: mapping.PciLegacyMapTypeArray{
//					&mapping.PciLegacyMapTypeArgs{
//						Comment:     pulumi.String("This is a device specific comment"),
//						Id:          pulumi.String("8086:5916"),
//						IommuGroup:  pulumi.Int(0),
//						Node:        pulumi.String("pve"),
//						Path:        pulumi.String("0000:00:02.0"),
//						SubsystemId: pulumi.String("8086:2068"),
//					},
//				},
//				MediatedDevices: pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// !/usr/bin/env sh
// A PCI hardware mapping can be imported using their name, e.g.:
//
// ```sh
// $ pulumi import proxmoxve:hardware/mapping/pciLegacy:PciLegacy example example
// ```
type PciLegacy struct {
	pulumi.CustomResourceState

	// The comment of this PCI hardware mapping.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// The actual map of devices for the PCI hardware mapping.
	Maps PciLegacyMapTypeArrayOutput `pulumi:"maps"`
	// Indicates whether to enable mediated devices.
	MediatedDevices pulumi.BoolOutput `pulumi:"mediatedDevices"`
	// The name of this PCI hardware mapping.
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewPciLegacy registers a new resource with the given unique name, arguments, and options.
func NewPciLegacy(ctx *pulumi.Context,
	name string, args *PciLegacyArgs, opts ...pulumi.ResourceOption) (*PciLegacy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Maps == nil {
		return nil, errors.New("invalid value for required argument 'Maps'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PciLegacy
	err := ctx.RegisterResource("proxmoxve:hardware/mapping/pciLegacy:PciLegacy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPciLegacy gets an existing PciLegacy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPciLegacy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PciLegacyState, opts ...pulumi.ResourceOption) (*PciLegacy, error) {
	var resource PciLegacy
	err := ctx.ReadResource("proxmoxve:hardware/mapping/pciLegacy:PciLegacy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PciLegacy resources.
type pciLegacyState struct {
	// The comment of this PCI hardware mapping.
	Comment *string `pulumi:"comment"`
	// The actual map of devices for the PCI hardware mapping.
	Maps []PciLegacyMapType `pulumi:"maps"`
	// Indicates whether to enable mediated devices.
	MediatedDevices *bool `pulumi:"mediatedDevices"`
	// The name of this PCI hardware mapping.
	Name *string `pulumi:"name"`
}

type PciLegacyState struct {
	// The comment of this PCI hardware mapping.
	Comment pulumi.StringPtrInput
	// The actual map of devices for the PCI hardware mapping.
	Maps PciLegacyMapTypeArrayInput
	// Indicates whether to enable mediated devices.
	MediatedDevices pulumi.BoolPtrInput
	// The name of this PCI hardware mapping.
	Name pulumi.StringPtrInput
}

func (PciLegacyState) ElementType() reflect.Type {
	return reflect.TypeOf((*pciLegacyState)(nil)).Elem()
}

type pciLegacyArgs struct {
	// The comment of this PCI hardware mapping.
	Comment *string `pulumi:"comment"`
	// The actual map of devices for the PCI hardware mapping.
	Maps []PciLegacyMapType `pulumi:"maps"`
	// Indicates whether to enable mediated devices.
	MediatedDevices *bool `pulumi:"mediatedDevices"`
	// The name of this PCI hardware mapping.
	Name *string `pulumi:"name"`
}

// The set of arguments for constructing a PciLegacy resource.
type PciLegacyArgs struct {
	// The comment of this PCI hardware mapping.
	Comment pulumi.StringPtrInput
	// The actual map of devices for the PCI hardware mapping.
	Maps PciLegacyMapTypeArrayInput
	// Indicates whether to enable mediated devices.
	MediatedDevices pulumi.BoolPtrInput
	// The name of this PCI hardware mapping.
	Name pulumi.StringPtrInput
}

func (PciLegacyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*pciLegacyArgs)(nil)).Elem()
}

type PciLegacyInput interface {
	pulumi.Input

	ToPciLegacyOutput() PciLegacyOutput
	ToPciLegacyOutputWithContext(ctx context.Context) PciLegacyOutput
}

func (*PciLegacy) ElementType() reflect.Type {
	return reflect.TypeOf((**PciLegacy)(nil)).Elem()
}

func (i *PciLegacy) ToPciLegacyOutput() PciLegacyOutput {
	return i.ToPciLegacyOutputWithContext(context.Background())
}

func (i *PciLegacy) ToPciLegacyOutputWithContext(ctx context.Context) PciLegacyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PciLegacyOutput)
}

// PciLegacyArrayInput is an input type that accepts PciLegacyArray and PciLegacyArrayOutput values.
// You can construct a concrete instance of `PciLegacyArrayInput` via:
//
//	PciLegacyArray{ PciLegacyArgs{...} }
type PciLegacyArrayInput interface {
	pulumi.Input

	ToPciLegacyArrayOutput() PciLegacyArrayOutput
	ToPciLegacyArrayOutputWithContext(context.Context) PciLegacyArrayOutput
}

type PciLegacyArray []PciLegacyInput

func (PciLegacyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PciLegacy)(nil)).Elem()
}

func (i PciLegacyArray) ToPciLegacyArrayOutput() PciLegacyArrayOutput {
	return i.ToPciLegacyArrayOutputWithContext(context.Background())
}

func (i PciLegacyArray) ToPciLegacyArrayOutputWithContext(ctx context.Context) PciLegacyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PciLegacyArrayOutput)
}

// PciLegacyMapInput is an input type that accepts PciLegacyMap and PciLegacyMapOutput values.
// You can construct a concrete instance of `PciLegacyMapInput` via:
//
//	PciLegacyMap{ "key": PciLegacyArgs{...} }
type PciLegacyMapInput interface {
	pulumi.Input

	ToPciLegacyMapOutput() PciLegacyMapOutput
	ToPciLegacyMapOutputWithContext(context.Context) PciLegacyMapOutput
}

type PciLegacyMap map[string]PciLegacyInput

func (PciLegacyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PciLegacy)(nil)).Elem()
}

func (i PciLegacyMap) ToPciLegacyMapOutput() PciLegacyMapOutput {
	return i.ToPciLegacyMapOutputWithContext(context.Background())
}

func (i PciLegacyMap) ToPciLegacyMapOutputWithContext(ctx context.Context) PciLegacyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PciLegacyMapOutput)
}

type PciLegacyOutput struct{ *pulumi.OutputState }

func (PciLegacyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PciLegacy)(nil)).Elem()
}

func (o PciLegacyOutput) ToPciLegacyOutput() PciLegacyOutput {
	return o
}

func (o PciLegacyOutput) ToPciLegacyOutputWithContext(ctx context.Context) PciLegacyOutput {
	return o
}

// The comment of this PCI hardware mapping.
func (o PciLegacyOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PciLegacy) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// The actual map of devices for the PCI hardware mapping.
func (o PciLegacyOutput) Maps() PciLegacyMapTypeArrayOutput {
	return o.ApplyT(func(v *PciLegacy) PciLegacyMapTypeArrayOutput { return v.Maps }).(PciLegacyMapTypeArrayOutput)
}

// Indicates whether to enable mediated devices.
func (o PciLegacyOutput) MediatedDevices() pulumi.BoolOutput {
	return o.ApplyT(func(v *PciLegacy) pulumi.BoolOutput { return v.MediatedDevices }).(pulumi.BoolOutput)
}

// The name of this PCI hardware mapping.
func (o PciLegacyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PciLegacy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type PciLegacyArrayOutput struct{ *pulumi.OutputState }

func (PciLegacyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PciLegacy)(nil)).Elem()
}

func (o PciLegacyArrayOutput) ToPciLegacyArrayOutput() PciLegacyArrayOutput {
	return o
}

func (o PciLegacyArrayOutput) ToPciLegacyArrayOutputWithContext(ctx context.Context) PciLegacyArrayOutput {
	return o
}

func (o PciLegacyArrayOutput) Index(i pulumi.IntInput) PciLegacyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PciLegacy {
		return vs[0].([]*PciLegacy)[vs[1].(int)]
	}).(PciLegacyOutput)
}

type PciLegacyMapOutput struct{ *pulumi.OutputState }

func (PciLegacyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PciLegacy)(nil)).Elem()
}

func (o PciLegacyMapOutput) ToPciLegacyMapOutput() PciLegacyMapOutput {
	return o
}

func (o PciLegacyMapOutput) ToPciLegacyMapOutputWithContext(ctx context.Context) PciLegacyMapOutput {
	return o
}

func (o PciLegacyMapOutput) MapIndex(k pulumi.StringInput) PciLegacyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PciLegacy {
		return vs[0].(map[string]*PciLegacy)[vs[1].(string)]
	}).(PciLegacyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PciLegacyInput)(nil)).Elem(), &PciLegacy{})
	pulumi.RegisterInputType(reflect.TypeOf((*PciLegacyArrayInput)(nil)).Elem(), PciLegacyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PciLegacyMapInput)(nil)).Elem(), PciLegacyMap{})
	pulumi.RegisterOutputType(PciLegacyOutput{})
	pulumi.RegisterOutputType(PciLegacyArrayOutput{})
	pulumi.RegisterOutputType(PciLegacyMapOutput{})
}
