// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ProxmoxVE.Network.Linux
{
    /// <summary>
    /// Manages a Linux Bridge network interface in a Proxmox VE node.
    /// </summary>
    [ProxmoxVEResourceType("proxmoxve:network/linux/bridge:Bridge")]
    public partial class Bridge : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The interface IPv4/CIDR address.
        /// </summary>
        [Output("address")]
        public Output<string?> Address { get; private set; } = null!;

        /// <summary>
        /// The interface IPv6/CIDR address.
        /// </summary>
        [Output("address6")]
        public Output<string?> Address6 { get; private set; } = null!;

        /// <summary>
        /// Automatically start interface on boot (defaults to `True`).
        /// </summary>
        [Output("autostart")]
        public Output<bool> Autostart { get; private set; } = null!;

        /// <summary>
        /// Comment for the interface.
        /// </summary>
        [Output("comment")]
        public Output<string?> Comment { get; private set; } = null!;

        /// <summary>
        /// Default gateway address.
        /// </summary>
        [Output("gateway")]
        public Output<string?> Gateway { get; private set; } = null!;

        /// <summary>
        /// Default IPv6 gateway address.
        /// </summary>
        [Output("gateway6")]
        public Output<string?> Gateway6 { get; private set; } = null!;

        /// <summary>
        /// The interface MTU.
        /// </summary>
        [Output("mtu")]
        public Output<int?> Mtu { get; private set; } = null!;

        /// <summary>
        /// The interface name. Commonly vmbr[N], where 0 ≤ N ≤ 4094 (vmbr0 - vmbr4094), but can be any alphanumeric string that starts with a character and is at most 10 characters long.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The name of the node.
        /// </summary>
        [Output("nodeName")]
        public Output<string> NodeName { get; private set; } = null!;

        /// <summary>
        /// The interface bridge ports.
        /// </summary>
        [Output("ports")]
        public Output<ImmutableArray<string>> Ports { get; private set; } = null!;

        /// <summary>
        /// Timeout for network reload operations in seconds (defaults to `100`).
        /// </summary>
        [Output("timeoutReload")]
        public Output<int> TimeoutReload { get; private set; } = null!;

        /// <summary>
        /// Whether the interface bridge is VLAN aware (defaults to `False`).
        /// </summary>
        [Output("vlanAware")]
        public Output<bool> VlanAware { get; private set; } = null!;


        /// <summary>
        /// Create a Bridge resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Bridge(string name, BridgeArgs args, CustomResourceOptions? options = null)
            : base("proxmoxve:network/linux/bridge:Bridge", name, args ?? new BridgeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Bridge(string name, Input<string> id, BridgeState? state = null, CustomResourceOptions? options = null)
            : base("proxmoxve:network/linux/bridge:Bridge", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/muhlba91/pulumi-proxmoxve",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Bridge resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Bridge Get(string name, Input<string> id, BridgeState? state = null, CustomResourceOptions? options = null)
        {
            return new Bridge(name, id, state, options);
        }
    }

    public sealed class BridgeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The interface IPv4/CIDR address.
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// The interface IPv6/CIDR address.
        /// </summary>
        [Input("address6")]
        public Input<string>? Address6 { get; set; }

        /// <summary>
        /// Automatically start interface on boot (defaults to `True`).
        /// </summary>
        [Input("autostart")]
        public Input<bool>? Autostart { get; set; }

        /// <summary>
        /// Comment for the interface.
        /// </summary>
        [Input("comment")]
        public Input<string>? Comment { get; set; }

        /// <summary>
        /// Default gateway address.
        /// </summary>
        [Input("gateway")]
        public Input<string>? Gateway { get; set; }

        /// <summary>
        /// Default IPv6 gateway address.
        /// </summary>
        [Input("gateway6")]
        public Input<string>? Gateway6 { get; set; }

        /// <summary>
        /// The interface MTU.
        /// </summary>
        [Input("mtu")]
        public Input<int>? Mtu { get; set; }

        /// <summary>
        /// The interface name. Commonly vmbr[N], where 0 ≤ N ≤ 4094 (vmbr0 - vmbr4094), but can be any alphanumeric string that starts with a character and is at most 10 characters long.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The name of the node.
        /// </summary>
        [Input("nodeName", required: true)]
        public Input<string> NodeName { get; set; } = null!;

        [Input("ports")]
        private InputList<string>? _ports;

        /// <summary>
        /// The interface bridge ports.
        /// </summary>
        public InputList<string> Ports
        {
            get => _ports ?? (_ports = new InputList<string>());
            set => _ports = value;
        }

        /// <summary>
        /// Timeout for network reload operations in seconds (defaults to `100`).
        /// </summary>
        [Input("timeoutReload")]
        public Input<int>? TimeoutReload { get; set; }

        /// <summary>
        /// Whether the interface bridge is VLAN aware (defaults to `False`).
        /// </summary>
        [Input("vlanAware")]
        public Input<bool>? VlanAware { get; set; }

        public BridgeArgs()
        {
        }
        public static new BridgeArgs Empty => new BridgeArgs();
    }

    public sealed class BridgeState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The interface IPv4/CIDR address.
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// The interface IPv6/CIDR address.
        /// </summary>
        [Input("address6")]
        public Input<string>? Address6 { get; set; }

        /// <summary>
        /// Automatically start interface on boot (defaults to `True`).
        /// </summary>
        [Input("autostart")]
        public Input<bool>? Autostart { get; set; }

        /// <summary>
        /// Comment for the interface.
        /// </summary>
        [Input("comment")]
        public Input<string>? Comment { get; set; }

        /// <summary>
        /// Default gateway address.
        /// </summary>
        [Input("gateway")]
        public Input<string>? Gateway { get; set; }

        /// <summary>
        /// Default IPv6 gateway address.
        /// </summary>
        [Input("gateway6")]
        public Input<string>? Gateway6 { get; set; }

        /// <summary>
        /// The interface MTU.
        /// </summary>
        [Input("mtu")]
        public Input<int>? Mtu { get; set; }

        /// <summary>
        /// The interface name. Commonly vmbr[N], where 0 ≤ N ≤ 4094 (vmbr0 - vmbr4094), but can be any alphanumeric string that starts with a character and is at most 10 characters long.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The name of the node.
        /// </summary>
        [Input("nodeName")]
        public Input<string>? NodeName { get; set; }

        [Input("ports")]
        private InputList<string>? _ports;

        /// <summary>
        /// The interface bridge ports.
        /// </summary>
        public InputList<string> Ports
        {
            get => _ports ?? (_ports = new InputList<string>());
            set => _ports = value;
        }

        /// <summary>
        /// Timeout for network reload operations in seconds (defaults to `100`).
        /// </summary>
        [Input("timeoutReload")]
        public Input<int>? TimeoutReload { get; set; }

        /// <summary>
        /// Whether the interface bridge is VLAN aware (defaults to `False`).
        /// </summary>
        [Input("vlanAware")]
        public Input<bool>? VlanAware { get; set; }

        public BridgeState()
        {
        }
        public static new BridgeState Empty => new BridgeState();
    }
}
