// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.muehlbachler.pulumi.proxmoxve.Hardware_mapping.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetUsbPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetUsbPlainArgs Empty = new GetUsbPlainArgs();

    /**
     * The name of this USB hardware mapping.
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return The name of this USB hardware mapping.
     * 
     */
    public String name() {
        return this.name;
    }

    private GetUsbPlainArgs() {}

    private GetUsbPlainArgs(GetUsbPlainArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetUsbPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetUsbPlainArgs $;

        public Builder() {
            $ = new GetUsbPlainArgs();
        }

        public Builder(GetUsbPlainArgs defaults) {
            $ = new GetUsbPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of this USB hardware mapping.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetUsbPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetUsbPlainArgs", "name");
            }
            return $;
        }
    }

}
