// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ProxmoxVE.Cluster.Inputs
{

    public sealed class OptionsNextIdArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The minimum number for the next free VM ID. Must be higher or equal to 100
        /// </summary>
        [Input("lower")]
        public Input<int>? Lower { get; set; }

        /// <summary>
        /// The maximum number for the next free VM ID. Must be less or equal to 999999999
        /// </summary>
        [Input("upper")]
        public Input<int>? Upper { get; set; }

        public OptionsNextIdArgs()
        {
        }
        public static new OptionsNextIdArgs Empty => new OptionsNextIdArgs();
    }
}
