// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ProxmoxVE.Acme
{
    /// <summary>
    /// Manages ACME SSL certificates for Proxmox VE nodes.
    /// 
    /// This resource orders and renews certificates from an ACME Certificate Authority (like Let's Encrypt) for a specific node. Before using this resource, ensure that:
    /// - An ACME account is configured (using `proxmoxve.acme.Account`)
    /// - DNS plugins are configured if using DNS-01 challenge (using `proxmoxve.acme/dns.Plugin`)
    /// </summary>
    [ProxmoxVEResourceType("proxmoxve:acme/certificate:Certificate")]
    public partial class Certificate : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ACME account name to use for ordering the certificate.
        /// </summary>
        [Output("account")]
        public Output<string> Account { get; private set; } = null!;

        /// <summary>
        /// The PEM-encoded certificate data.
        /// </summary>
        [Output("certificate")]
        public Output<string> certificatePem { get; private set; } = null!;

        /// <summary>
        /// The list of domains to include in the certificate. At least one domain is required.
        /// </summary>
        [Output("domains")]
        public Output<ImmutableArray<Outputs.CertificateDomain>> Domains { get; private set; } = null!;

        /// <summary>
        /// The certificate fingerprint.
        /// </summary>
        [Output("fingerprint")]
        public Output<string> Fingerprint { get; private set; } = null!;

        /// <summary>
        /// Force certificate renewal even if the certificate is not due for renewal yet. Setting this to true will trigger a new certificate order on every apply.
        /// </summary>
        [Output("force")]
        public Output<bool> Force { get; private set; } = null!;

        /// <summary>
        /// The certificate issuer.
        /// </summary>
        [Output("issuer")]
        public Output<string> Issuer { get; private set; } = null!;

        /// <summary>
        /// The name of the Proxmox VE node for which to order/manage the ACME certificate.
        /// </summary>
        [Output("nodeName")]
        public Output<string> NodeName { get; private set; } = null!;

        /// <summary>
        /// The certificate expiration timestamp.
        /// </summary>
        [Output("notAfter")]
        public Output<string> NotAfter { get; private set; } = null!;

        /// <summary>
        /// The certificate start timestamp.
        /// </summary>
        [Output("notBefore")]
        public Output<string> NotBefore { get; private set; } = null!;

        /// <summary>
        /// The certificate subject.
        /// </summary>
        [Output("subject")]
        public Output<string> Subject { get; private set; } = null!;

        /// <summary>
        /// The certificate subject alternative names (SANs).
        /// </summary>
        [Output("subjectAlternativeNames")]
        public Output<ImmutableArray<string>> SubjectAlternativeNames { get; private set; } = null!;


        /// <summary>
        /// Create a Certificate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Certificate(string name, CertificateArgs args, CustomResourceOptions? options = null)
            : base("proxmoxve:acme/certificate:Certificate", name, args ?? new CertificateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Certificate(string name, Input<string> id, CertificateState? state = null, CustomResourceOptions? options = null)
            : base("proxmoxve:acme/certificate:Certificate", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/muhlba91/pulumi-proxmoxve",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Certificate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Certificate Get(string name, Input<string> id, CertificateState? state = null, CustomResourceOptions? options = null)
        {
            return new Certificate(name, id, state, options);
        }
    }

    public sealed class CertificateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ACME account name to use for ordering the certificate.
        /// </summary>
        [Input("account", required: true)]
        public Input<string> Account { get; set; } = null!;

        [Input("domains", required: true)]
        private InputList<Inputs.CertificateDomainArgs>? _domains;

        /// <summary>
        /// The list of domains to include in the certificate. At least one domain is required.
        /// </summary>
        public InputList<Inputs.CertificateDomainArgs> Domains
        {
            get => _domains ?? (_domains = new InputList<Inputs.CertificateDomainArgs>());
            set => _domains = value;
        }

        /// <summary>
        /// Force certificate renewal even if the certificate is not due for renewal yet. Setting this to true will trigger a new certificate order on every apply.
        /// </summary>
        [Input("force")]
        public Input<bool>? Force { get; set; }

        /// <summary>
        /// The name of the Proxmox VE node for which to order/manage the ACME certificate.
        /// </summary>
        [Input("nodeName", required: true)]
        public Input<string> NodeName { get; set; } = null!;

        public CertificateArgs()
        {
        }
        public static new CertificateArgs Empty => new CertificateArgs();
    }

    public sealed class CertificateState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ACME account name to use for ordering the certificate.
        /// </summary>
        [Input("account")]
        public Input<string>? Account { get; set; }

        /// <summary>
        /// The PEM-encoded certificate data.
        /// </summary>
        [Input("certificate")]
        public Input<string>? certificatePem { get; set; }

        [Input("domains")]
        private InputList<Inputs.CertificateDomainGetArgs>? _domains;

        /// <summary>
        /// The list of domains to include in the certificate. At least one domain is required.
        /// </summary>
        public InputList<Inputs.CertificateDomainGetArgs> Domains
        {
            get => _domains ?? (_domains = new InputList<Inputs.CertificateDomainGetArgs>());
            set => _domains = value;
        }

        /// <summary>
        /// The certificate fingerprint.
        /// </summary>
        [Input("fingerprint")]
        public Input<string>? Fingerprint { get; set; }

        /// <summary>
        /// Force certificate renewal even if the certificate is not due for renewal yet. Setting this to true will trigger a new certificate order on every apply.
        /// </summary>
        [Input("force")]
        public Input<bool>? Force { get; set; }

        /// <summary>
        /// The certificate issuer.
        /// </summary>
        [Input("issuer")]
        public Input<string>? Issuer { get; set; }

        /// <summary>
        /// The name of the Proxmox VE node for which to order/manage the ACME certificate.
        /// </summary>
        [Input("nodeName")]
        public Input<string>? NodeName { get; set; }

        /// <summary>
        /// The certificate expiration timestamp.
        /// </summary>
        [Input("notAfter")]
        public Input<string>? NotAfter { get; set; }

        /// <summary>
        /// The certificate start timestamp.
        /// </summary>
        [Input("notBefore")]
        public Input<string>? NotBefore { get; set; }

        /// <summary>
        /// The certificate subject.
        /// </summary>
        [Input("subject")]
        public Input<string>? Subject { get; set; }

        [Input("subjectAlternativeNames")]
        private InputList<string>? _subjectAlternativeNames;

        /// <summary>
        /// The certificate subject alternative names (SANs).
        /// </summary>
        public InputList<string> SubjectAlternativeNames
        {
            get => _subjectAlternativeNames ?? (_subjectAlternativeNames = new InputList<string>());
            set => _subjectAlternativeNames = value;
        }

        public CertificateState()
        {
        }
        public static new CertificateState Empty => new CertificateState();
    }
}
