// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ProxmoxVE.Acme
{
    public static class GetPluginsLegacy
    {
        /// <summary>
        /// &gt; **Deprecated:** Use `proxmoxve.acme.getPlugins` instead. This data source will be removed in v1.0.
        /// 
        /// Retrieves the list of ACME plugins.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using ProxmoxVE = Pulumi.ProxmoxVE;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = ProxmoxVE.Acme.GetPluginsLegacy.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["dataProxmoxVirtualEnvironmentAcmePlugins"] = example.Apply(getPluginsLegacyResult =&gt; getPluginsLegacyResult.Plugins),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetPluginsLegacyResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPluginsLegacyResult>("proxmoxve:acme/getPluginsLegacy:getPluginsLegacy", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// &gt; **Deprecated:** Use `proxmoxve.acme.getPlugins` instead. This data source will be removed in v1.0.
        /// 
        /// Retrieves the list of ACME plugins.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using ProxmoxVE = Pulumi.ProxmoxVE;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = ProxmoxVE.Acme.GetPluginsLegacy.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["dataProxmoxVirtualEnvironmentAcmePlugins"] = example.Apply(getPluginsLegacyResult =&gt; getPluginsLegacyResult.Plugins),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetPluginsLegacyResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPluginsLegacyResult>("proxmoxve:acme/getPluginsLegacy:getPluginsLegacy", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// &gt; **Deprecated:** Use `proxmoxve.acme.getPlugins` instead. This data source will be removed in v1.0.
        /// 
        /// Retrieves the list of ACME plugins.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using ProxmoxVE = Pulumi.ProxmoxVE;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = ProxmoxVE.Acme.GetPluginsLegacy.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["dataProxmoxVirtualEnvironmentAcmePlugins"] = example.Apply(getPluginsLegacyResult =&gt; getPluginsLegacyResult.Plugins),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetPluginsLegacyResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPluginsLegacyResult>("proxmoxve:acme/getPluginsLegacy:getPluginsLegacy", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetPluginsLegacyResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of ACME plugins
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPluginsLegacyPluginResult> Plugins;

        [OutputConstructor]
        private GetPluginsLegacyResult(
            string id,

            ImmutableArray<Outputs.GetPluginsLegacyPluginResult> plugins)
        {
            Id = id;
            Plugins = plugins;
        }
    }
}
