// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.muehlbachler.pulumi.proxmoxve.ceph;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PoolArgs extends com.pulumi.resources.ResourceArgs {

    public static final PoolArgs Empty = new PoolArgs();

    /**
     * Configure VM and CT storage entries using the new pool. Applied at create time only; changing this value forces replacement.
     * 
     */
    @Import(name="addStorages")
    private @Nullable Output<Boolean> addStorages;

    /**
     * @return Configure VM and CT storage entries using the new pool. Applied at create time only; changing this value forces replacement.
     * 
     */
    public Optional<Output<Boolean>> addStorages() {
        return Optional.ofNullable(this.addStorages);
    }

    /**
     * The application using the pool. One of &lt;span pulumi-lang-nodejs=&#34;`rbd`&#34; pulumi-lang-dotnet=&#34;`Rbd`&#34; pulumi-lang-go=&#34;`rbd`&#34; pulumi-lang-python=&#34;`rbd`&#34; pulumi-lang-yaml=&#34;`rbd`&#34; pulumi-lang-java=&#34;`rbd`&#34; pulumi-lang-hcl=&#34;`rbd`&#34;&gt;`rbd`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`cephfs`&#34; pulumi-lang-dotnet=&#34;`Cephfs`&#34; pulumi-lang-go=&#34;`cephfs`&#34; pulumi-lang-python=&#34;`cephfs`&#34; pulumi-lang-yaml=&#34;`cephfs`&#34; pulumi-lang-java=&#34;`cephfs`&#34; pulumi-lang-hcl=&#34;`cephfs`&#34;&gt;`cephfs`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`rgw`&#34; pulumi-lang-dotnet=&#34;`Rgw`&#34; pulumi-lang-go=&#34;`rgw`&#34; pulumi-lang-python=&#34;`rgw`&#34; pulumi-lang-yaml=&#34;`rgw`&#34; pulumi-lang-java=&#34;`rgw`&#34; pulumi-lang-hcl=&#34;`rgw`&#34;&gt;`rgw`&lt;/span&gt;. Defaults to &lt;span pulumi-lang-nodejs=&#34;`rbd`&#34; pulumi-lang-dotnet=&#34;`Rbd`&#34; pulumi-lang-go=&#34;`rbd`&#34; pulumi-lang-python=&#34;`rbd`&#34; pulumi-lang-yaml=&#34;`rbd`&#34; pulumi-lang-java=&#34;`rbd`&#34; pulumi-lang-hcl=&#34;`rbd`&#34;&gt;`rbd`&lt;/span&gt; server-side.
     * 
     */
    @Import(name="application")
    private @Nullable Output<String> application;

    /**
     * @return The application using the pool. One of &lt;span pulumi-lang-nodejs=&#34;`rbd`&#34; pulumi-lang-dotnet=&#34;`Rbd`&#34; pulumi-lang-go=&#34;`rbd`&#34; pulumi-lang-python=&#34;`rbd`&#34; pulumi-lang-yaml=&#34;`rbd`&#34; pulumi-lang-java=&#34;`rbd`&#34; pulumi-lang-hcl=&#34;`rbd`&#34;&gt;`rbd`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`cephfs`&#34; pulumi-lang-dotnet=&#34;`Cephfs`&#34; pulumi-lang-go=&#34;`cephfs`&#34; pulumi-lang-python=&#34;`cephfs`&#34; pulumi-lang-yaml=&#34;`cephfs`&#34; pulumi-lang-java=&#34;`cephfs`&#34; pulumi-lang-hcl=&#34;`cephfs`&#34;&gt;`cephfs`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`rgw`&#34; pulumi-lang-dotnet=&#34;`Rgw`&#34; pulumi-lang-go=&#34;`rgw`&#34; pulumi-lang-python=&#34;`rgw`&#34; pulumi-lang-yaml=&#34;`rgw`&#34; pulumi-lang-java=&#34;`rgw`&#34; pulumi-lang-hcl=&#34;`rgw`&#34;&gt;`rgw`&lt;/span&gt;. Defaults to &lt;span pulumi-lang-nodejs=&#34;`rbd`&#34; pulumi-lang-dotnet=&#34;`Rbd`&#34; pulumi-lang-go=&#34;`rbd`&#34; pulumi-lang-python=&#34;`rbd`&#34; pulumi-lang-yaml=&#34;`rbd`&#34; pulumi-lang-java=&#34;`rbd`&#34; pulumi-lang-hcl=&#34;`rbd`&#34;&gt;`rbd`&lt;/span&gt; server-side.
     * 
     */
    public Optional<Output<String>> application() {
        return Optional.ofNullable(this.application);
    }

    /**
     * The CRUSH rule name used for object placement.
     * 
     */
    @Import(name="crushRule")
    private @Nullable Output<String> crushRule;

    /**
     * @return The CRUSH rule name used for object placement.
     * 
     */
    public Optional<Output<String>> crushRule() {
        return Optional.ofNullable(this.crushRule);
    }

    /**
     * Create an erasure coded pool. Specified as `k=&lt;int&gt;,m=&lt;int&gt;[,profile=name][,device-class=class][,failure-domain=domain]` (e.g. `k=4,m=2`). Cannot be changed after creation.
     * 
     */
    @Import(name="erasureCoding")
    private @Nullable Output<String> erasureCoding;

    /**
     * @return Create an erasure coded pool. Specified as `k=&lt;int&gt;,m=&lt;int&gt;[,profile=name][,device-class=class][,failure-domain=domain]` (e.g. `k=4,m=2`). Cannot be changed after creation.
     * 
     */
    public Optional<Output<String>> erasureCoding() {
        return Optional.ofNullable(this.erasureCoding);
    }

    /**
     * If true, destroy the pool even when in use. Passed as `force=1` on delete.
     * 
     */
    @Import(name="forceDestroy")
    private @Nullable Output<Boolean> forceDestroy;

    /**
     * @return If true, destroy the pool even when in use. Passed as `force=1` on delete.
     * 
     */
    public Optional<Output<Boolean>> forceDestroy() {
        return Optional.ofNullable(this.forceDestroy);
    }

    /**
     * Minimum number of replicas per object.
     * 
     */
    @Import(name="minSize")
    private @Nullable Output<Integer> minSize;

    /**
     * @return Minimum number of replicas per object.
     * 
     */
    public Optional<Output<Integer>> minSize() {
        return Optional.ofNullable(this.minSize);
    }

    /**
     * The pool name. Must be unique within the Ceph cluster.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The pool name. Must be unique within the Ceph cluster.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The cluster node used to dispatch the API call. Any node running Ceph is acceptable; the pool itself is cluster-wide.
     * 
     */
    @Import(name="nodeName", required=true)
    private Output<String> nodeName;

    /**
     * @return The cluster node used to dispatch the API call. Any node running Ceph is acceptable; the pool itself is cluster-wide.
     * 
     */
    public Output<String> nodeName() {
        return this.nodeName;
    }

    /**
     * PG autoscaler mode. One of &lt;span pulumi-lang-nodejs=&#34;`on`&#34; pulumi-lang-dotnet=&#34;`On`&#34; pulumi-lang-go=&#34;`on`&#34; pulumi-lang-python=&#34;`on`&#34; pulumi-lang-yaml=&#34;`on`&#34; pulumi-lang-java=&#34;`on`&#34; pulumi-lang-hcl=&#34;`on`&#34;&gt;`on`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`off`&#34; pulumi-lang-dotnet=&#34;`Off`&#34; pulumi-lang-go=&#34;`off`&#34; pulumi-lang-python=&#34;`off`&#34; pulumi-lang-yaml=&#34;`off`&#34; pulumi-lang-java=&#34;`off`&#34; pulumi-lang-hcl=&#34;`off`&#34;&gt;`off`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`warn`&#34; pulumi-lang-dotnet=&#34;`Warn`&#34; pulumi-lang-go=&#34;`warn`&#34; pulumi-lang-python=&#34;`warn`&#34; pulumi-lang-yaml=&#34;`warn`&#34; pulumi-lang-java=&#34;`warn`&#34; pulumi-lang-hcl=&#34;`warn`&#34;&gt;`warn`&lt;/span&gt;.
     * 
     */
    @Import(name="pgAutoscaleMode")
    private @Nullable Output<String> pgAutoscaleMode;

    /**
     * @return PG autoscaler mode. One of &lt;span pulumi-lang-nodejs=&#34;`on`&#34; pulumi-lang-dotnet=&#34;`On`&#34; pulumi-lang-go=&#34;`on`&#34; pulumi-lang-python=&#34;`on`&#34; pulumi-lang-yaml=&#34;`on`&#34; pulumi-lang-java=&#34;`on`&#34; pulumi-lang-hcl=&#34;`on`&#34;&gt;`on`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`off`&#34; pulumi-lang-dotnet=&#34;`Off`&#34; pulumi-lang-go=&#34;`off`&#34; pulumi-lang-python=&#34;`off`&#34; pulumi-lang-yaml=&#34;`off`&#34; pulumi-lang-java=&#34;`off`&#34; pulumi-lang-hcl=&#34;`off`&#34;&gt;`off`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`warn`&#34; pulumi-lang-dotnet=&#34;`Warn`&#34; pulumi-lang-go=&#34;`warn`&#34; pulumi-lang-python=&#34;`warn`&#34; pulumi-lang-yaml=&#34;`warn`&#34; pulumi-lang-java=&#34;`warn`&#34; pulumi-lang-hcl=&#34;`warn`&#34;&gt;`warn`&lt;/span&gt;.
     * 
     */
    public Optional<Output<String>> pgAutoscaleMode() {
        return Optional.ofNullable(this.pgAutoscaleMode);
    }

    /**
     * Number of placement groups.
     * 
     */
    @Import(name="pgNum")
    private @Nullable Output<Integer> pgNum;

    /**
     * @return Number of placement groups.
     * 
     */
    public Optional<Output<Integer>> pgNum() {
        return Optional.ofNullable(this.pgNum);
    }

    /**
     * Minimum number of placement groups (used by the autoscaler).
     * 
     */
    @Import(name="pgNumMin")
    private @Nullable Output<Integer> pgNumMin;

    /**
     * @return Minimum number of placement groups (used by the autoscaler).
     * 
     */
    public Optional<Output<Integer>> pgNumMin() {
        return Optional.ofNullable(this.pgNumMin);
    }

    /**
     * If true, remove the erasure code profile on destroy. Defaults to true. Only relevant for EC pools.
     * 
     */
    @Import(name="removeEcprofile")
    private @Nullable Output<Boolean> removeEcprofile;

    /**
     * @return If true, remove the erasure code profile on destroy. Defaults to true. Only relevant for EC pools.
     * 
     */
    public Optional<Output<Boolean>> removeEcprofile() {
        return Optional.ofNullable(this.removeEcprofile);
    }

    /**
     * If true, remove all pveceph-managed storages configured for this pool on destroy.
     * 
     */
    @Import(name="removeStorages")
    private @Nullable Output<Boolean> removeStorages;

    /**
     * @return If true, remove all pveceph-managed storages configured for this pool on destroy.
     * 
     */
    public Optional<Output<Boolean>> removeStorages() {
        return Optional.ofNullable(this.removeStorages);
    }

    /**
     * Number of replicas per object.
     * 
     */
    @Import(name="size")
    private @Nullable Output<Integer> size;

    /**
     * @return Number of replicas per object.
     * 
     */
    public Optional<Output<Integer>> size() {
        return Optional.ofNullable(this.size);
    }

    /**
     * Estimated target size for the PG autoscaler (e.g. `100G`). **Write-only:** PVE returns this as a bytes integer (e.g. &lt;span pulumi-lang-nodejs=&#34;`1073741824`&#34; pulumi-lang-dotnet=&#34;`1073741824`&#34; pulumi-lang-go=&#34;`1073741824`&#34; pulumi-lang-python=&#34;`1073741824`&#34; pulumi-lang-yaml=&#34;`1073741824`&#34; pulumi-lang-java=&#34;`1073741824`&#34; pulumi-lang-hcl=&#34;`1073741824`&#34;&gt;`1073741824`&lt;/span&gt;) while the input accepts a unit-suffixed string, so the configured spec is not round-tripped from the server.
     * 
     */
    @Import(name="targetSize")
    private @Nullable Output<String> targetSize;

    /**
     * @return Estimated target size for the PG autoscaler (e.g. `100G`). **Write-only:** PVE returns this as a bytes integer (e.g. &lt;span pulumi-lang-nodejs=&#34;`1073741824`&#34; pulumi-lang-dotnet=&#34;`1073741824`&#34; pulumi-lang-go=&#34;`1073741824`&#34; pulumi-lang-python=&#34;`1073741824`&#34; pulumi-lang-yaml=&#34;`1073741824`&#34; pulumi-lang-java=&#34;`1073741824`&#34; pulumi-lang-hcl=&#34;`1073741824`&#34;&gt;`1073741824`&lt;/span&gt;) while the input accepts a unit-suffixed string, so the configured spec is not round-tripped from the server.
     * 
     */
    public Optional<Output<String>> targetSize() {
        return Optional.ofNullable(this.targetSize);
    }

    /**
     * Estimated target ratio for the PG autoscaler. **Write-only:** kept symmetric with &lt;span pulumi-lang-nodejs=&#34;`targetSize`&#34; pulumi-lang-dotnet=&#34;`TargetSize`&#34; pulumi-lang-go=&#34;`targetSize`&#34; pulumi-lang-python=&#34;`target_size`&#34; pulumi-lang-yaml=&#34;`targetSize`&#34; pulumi-lang-java=&#34;`targetSize`&#34; pulumi-lang-hcl=&#34;`target_size`&#34;&gt;`targetSize`&lt;/span&gt; (which cannot be round-tripped), so the configured value is not refreshed from the server.
     * 
     */
    @Import(name="targetSizeRatio")
    private @Nullable Output<Double> targetSizeRatio;

    /**
     * @return Estimated target ratio for the PG autoscaler. **Write-only:** kept symmetric with &lt;span pulumi-lang-nodejs=&#34;`targetSize`&#34; pulumi-lang-dotnet=&#34;`TargetSize`&#34; pulumi-lang-go=&#34;`targetSize`&#34; pulumi-lang-python=&#34;`target_size`&#34; pulumi-lang-yaml=&#34;`targetSize`&#34; pulumi-lang-java=&#34;`targetSize`&#34; pulumi-lang-hcl=&#34;`target_size`&#34;&gt;`targetSize`&lt;/span&gt; (which cannot be round-tripped), so the configured value is not refreshed from the server.
     * 
     */
    public Optional<Output<Double>> targetSizeRatio() {
        return Optional.ofNullable(this.targetSizeRatio);
    }

    private PoolArgs() {}

    private PoolArgs(PoolArgs $) {
        this.addStorages = $.addStorages;
        this.application = $.application;
        this.crushRule = $.crushRule;
        this.erasureCoding = $.erasureCoding;
        this.forceDestroy = $.forceDestroy;
        this.minSize = $.minSize;
        this.name = $.name;
        this.nodeName = $.nodeName;
        this.pgAutoscaleMode = $.pgAutoscaleMode;
        this.pgNum = $.pgNum;
        this.pgNumMin = $.pgNumMin;
        this.removeEcprofile = $.removeEcprofile;
        this.removeStorages = $.removeStorages;
        this.size = $.size;
        this.targetSize = $.targetSize;
        this.targetSizeRatio = $.targetSizeRatio;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PoolArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PoolArgs $;

        public Builder() {
            $ = new PoolArgs();
        }

        public Builder(PoolArgs defaults) {
            $ = new PoolArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param addStorages Configure VM and CT storage entries using the new pool. Applied at create time only; changing this value forces replacement.
         * 
         * @return builder
         * 
         */
        public Builder addStorages(@Nullable Output<Boolean> addStorages) {
            $.addStorages = addStorages;
            return this;
        }

        /**
         * @param addStorages Configure VM and CT storage entries using the new pool. Applied at create time only; changing this value forces replacement.
         * 
         * @return builder
         * 
         */
        public Builder addStorages(Boolean addStorages) {
            return addStorages(Output.of(addStorages));
        }

        /**
         * @param application The application using the pool. One of &lt;span pulumi-lang-nodejs=&#34;`rbd`&#34; pulumi-lang-dotnet=&#34;`Rbd`&#34; pulumi-lang-go=&#34;`rbd`&#34; pulumi-lang-python=&#34;`rbd`&#34; pulumi-lang-yaml=&#34;`rbd`&#34; pulumi-lang-java=&#34;`rbd`&#34; pulumi-lang-hcl=&#34;`rbd`&#34;&gt;`rbd`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`cephfs`&#34; pulumi-lang-dotnet=&#34;`Cephfs`&#34; pulumi-lang-go=&#34;`cephfs`&#34; pulumi-lang-python=&#34;`cephfs`&#34; pulumi-lang-yaml=&#34;`cephfs`&#34; pulumi-lang-java=&#34;`cephfs`&#34; pulumi-lang-hcl=&#34;`cephfs`&#34;&gt;`cephfs`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`rgw`&#34; pulumi-lang-dotnet=&#34;`Rgw`&#34; pulumi-lang-go=&#34;`rgw`&#34; pulumi-lang-python=&#34;`rgw`&#34; pulumi-lang-yaml=&#34;`rgw`&#34; pulumi-lang-java=&#34;`rgw`&#34; pulumi-lang-hcl=&#34;`rgw`&#34;&gt;`rgw`&lt;/span&gt;. Defaults to &lt;span pulumi-lang-nodejs=&#34;`rbd`&#34; pulumi-lang-dotnet=&#34;`Rbd`&#34; pulumi-lang-go=&#34;`rbd`&#34; pulumi-lang-python=&#34;`rbd`&#34; pulumi-lang-yaml=&#34;`rbd`&#34; pulumi-lang-java=&#34;`rbd`&#34; pulumi-lang-hcl=&#34;`rbd`&#34;&gt;`rbd`&lt;/span&gt; server-side.
         * 
         * @return builder
         * 
         */
        public Builder application(@Nullable Output<String> application) {
            $.application = application;
            return this;
        }

        /**
         * @param application The application using the pool. One of &lt;span pulumi-lang-nodejs=&#34;`rbd`&#34; pulumi-lang-dotnet=&#34;`Rbd`&#34; pulumi-lang-go=&#34;`rbd`&#34; pulumi-lang-python=&#34;`rbd`&#34; pulumi-lang-yaml=&#34;`rbd`&#34; pulumi-lang-java=&#34;`rbd`&#34; pulumi-lang-hcl=&#34;`rbd`&#34;&gt;`rbd`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`cephfs`&#34; pulumi-lang-dotnet=&#34;`Cephfs`&#34; pulumi-lang-go=&#34;`cephfs`&#34; pulumi-lang-python=&#34;`cephfs`&#34; pulumi-lang-yaml=&#34;`cephfs`&#34; pulumi-lang-java=&#34;`cephfs`&#34; pulumi-lang-hcl=&#34;`cephfs`&#34;&gt;`cephfs`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`rgw`&#34; pulumi-lang-dotnet=&#34;`Rgw`&#34; pulumi-lang-go=&#34;`rgw`&#34; pulumi-lang-python=&#34;`rgw`&#34; pulumi-lang-yaml=&#34;`rgw`&#34; pulumi-lang-java=&#34;`rgw`&#34; pulumi-lang-hcl=&#34;`rgw`&#34;&gt;`rgw`&lt;/span&gt;. Defaults to &lt;span pulumi-lang-nodejs=&#34;`rbd`&#34; pulumi-lang-dotnet=&#34;`Rbd`&#34; pulumi-lang-go=&#34;`rbd`&#34; pulumi-lang-python=&#34;`rbd`&#34; pulumi-lang-yaml=&#34;`rbd`&#34; pulumi-lang-java=&#34;`rbd`&#34; pulumi-lang-hcl=&#34;`rbd`&#34;&gt;`rbd`&lt;/span&gt; server-side.
         * 
         * @return builder
         * 
         */
        public Builder application(String application) {
            return application(Output.of(application));
        }

        /**
         * @param crushRule The CRUSH rule name used for object placement.
         * 
         * @return builder
         * 
         */
        public Builder crushRule(@Nullable Output<String> crushRule) {
            $.crushRule = crushRule;
            return this;
        }

        /**
         * @param crushRule The CRUSH rule name used for object placement.
         * 
         * @return builder
         * 
         */
        public Builder crushRule(String crushRule) {
            return crushRule(Output.of(crushRule));
        }

        /**
         * @param erasureCoding Create an erasure coded pool. Specified as `k=&lt;int&gt;,m=&lt;int&gt;[,profile=name][,device-class=class][,failure-domain=domain]` (e.g. `k=4,m=2`). Cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder erasureCoding(@Nullable Output<String> erasureCoding) {
            $.erasureCoding = erasureCoding;
            return this;
        }

        /**
         * @param erasureCoding Create an erasure coded pool. Specified as `k=&lt;int&gt;,m=&lt;int&gt;[,profile=name][,device-class=class][,failure-domain=domain]` (e.g. `k=4,m=2`). Cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder erasureCoding(String erasureCoding) {
            return erasureCoding(Output.of(erasureCoding));
        }

        /**
         * @param forceDestroy If true, destroy the pool even when in use. Passed as `force=1` on delete.
         * 
         * @return builder
         * 
         */
        public Builder forceDestroy(@Nullable Output<Boolean> forceDestroy) {
            $.forceDestroy = forceDestroy;
            return this;
        }

        /**
         * @param forceDestroy If true, destroy the pool even when in use. Passed as `force=1` on delete.
         * 
         * @return builder
         * 
         */
        public Builder forceDestroy(Boolean forceDestroy) {
            return forceDestroy(Output.of(forceDestroy));
        }

        /**
         * @param minSize Minimum number of replicas per object.
         * 
         * @return builder
         * 
         */
        public Builder minSize(@Nullable Output<Integer> minSize) {
            $.minSize = minSize;
            return this;
        }

        /**
         * @param minSize Minimum number of replicas per object.
         * 
         * @return builder
         * 
         */
        public Builder minSize(Integer minSize) {
            return minSize(Output.of(minSize));
        }

        /**
         * @param name The pool name. Must be unique within the Ceph cluster.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The pool name. Must be unique within the Ceph cluster.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param nodeName The cluster node used to dispatch the API call. Any node running Ceph is acceptable; the pool itself is cluster-wide.
         * 
         * @return builder
         * 
         */
        public Builder nodeName(Output<String> nodeName) {
            $.nodeName = nodeName;
            return this;
        }

        /**
         * @param nodeName The cluster node used to dispatch the API call. Any node running Ceph is acceptable; the pool itself is cluster-wide.
         * 
         * @return builder
         * 
         */
        public Builder nodeName(String nodeName) {
            return nodeName(Output.of(nodeName));
        }

        /**
         * @param pgAutoscaleMode PG autoscaler mode. One of &lt;span pulumi-lang-nodejs=&#34;`on`&#34; pulumi-lang-dotnet=&#34;`On`&#34; pulumi-lang-go=&#34;`on`&#34; pulumi-lang-python=&#34;`on`&#34; pulumi-lang-yaml=&#34;`on`&#34; pulumi-lang-java=&#34;`on`&#34; pulumi-lang-hcl=&#34;`on`&#34;&gt;`on`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`off`&#34; pulumi-lang-dotnet=&#34;`Off`&#34; pulumi-lang-go=&#34;`off`&#34; pulumi-lang-python=&#34;`off`&#34; pulumi-lang-yaml=&#34;`off`&#34; pulumi-lang-java=&#34;`off`&#34; pulumi-lang-hcl=&#34;`off`&#34;&gt;`off`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`warn`&#34; pulumi-lang-dotnet=&#34;`Warn`&#34; pulumi-lang-go=&#34;`warn`&#34; pulumi-lang-python=&#34;`warn`&#34; pulumi-lang-yaml=&#34;`warn`&#34; pulumi-lang-java=&#34;`warn`&#34; pulumi-lang-hcl=&#34;`warn`&#34;&gt;`warn`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder pgAutoscaleMode(@Nullable Output<String> pgAutoscaleMode) {
            $.pgAutoscaleMode = pgAutoscaleMode;
            return this;
        }

        /**
         * @param pgAutoscaleMode PG autoscaler mode. One of &lt;span pulumi-lang-nodejs=&#34;`on`&#34; pulumi-lang-dotnet=&#34;`On`&#34; pulumi-lang-go=&#34;`on`&#34; pulumi-lang-python=&#34;`on`&#34; pulumi-lang-yaml=&#34;`on`&#34; pulumi-lang-java=&#34;`on`&#34; pulumi-lang-hcl=&#34;`on`&#34;&gt;`on`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`off`&#34; pulumi-lang-dotnet=&#34;`Off`&#34; pulumi-lang-go=&#34;`off`&#34; pulumi-lang-python=&#34;`off`&#34; pulumi-lang-yaml=&#34;`off`&#34; pulumi-lang-java=&#34;`off`&#34; pulumi-lang-hcl=&#34;`off`&#34;&gt;`off`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`warn`&#34; pulumi-lang-dotnet=&#34;`Warn`&#34; pulumi-lang-go=&#34;`warn`&#34; pulumi-lang-python=&#34;`warn`&#34; pulumi-lang-yaml=&#34;`warn`&#34; pulumi-lang-java=&#34;`warn`&#34; pulumi-lang-hcl=&#34;`warn`&#34;&gt;`warn`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder pgAutoscaleMode(String pgAutoscaleMode) {
            return pgAutoscaleMode(Output.of(pgAutoscaleMode));
        }

        /**
         * @param pgNum Number of placement groups.
         * 
         * @return builder
         * 
         */
        public Builder pgNum(@Nullable Output<Integer> pgNum) {
            $.pgNum = pgNum;
            return this;
        }

        /**
         * @param pgNum Number of placement groups.
         * 
         * @return builder
         * 
         */
        public Builder pgNum(Integer pgNum) {
            return pgNum(Output.of(pgNum));
        }

        /**
         * @param pgNumMin Minimum number of placement groups (used by the autoscaler).
         * 
         * @return builder
         * 
         */
        public Builder pgNumMin(@Nullable Output<Integer> pgNumMin) {
            $.pgNumMin = pgNumMin;
            return this;
        }

        /**
         * @param pgNumMin Minimum number of placement groups (used by the autoscaler).
         * 
         * @return builder
         * 
         */
        public Builder pgNumMin(Integer pgNumMin) {
            return pgNumMin(Output.of(pgNumMin));
        }

        /**
         * @param removeEcprofile If true, remove the erasure code profile on destroy. Defaults to true. Only relevant for EC pools.
         * 
         * @return builder
         * 
         */
        public Builder removeEcprofile(@Nullable Output<Boolean> removeEcprofile) {
            $.removeEcprofile = removeEcprofile;
            return this;
        }

        /**
         * @param removeEcprofile If true, remove the erasure code profile on destroy. Defaults to true. Only relevant for EC pools.
         * 
         * @return builder
         * 
         */
        public Builder removeEcprofile(Boolean removeEcprofile) {
            return removeEcprofile(Output.of(removeEcprofile));
        }

        /**
         * @param removeStorages If true, remove all pveceph-managed storages configured for this pool on destroy.
         * 
         * @return builder
         * 
         */
        public Builder removeStorages(@Nullable Output<Boolean> removeStorages) {
            $.removeStorages = removeStorages;
            return this;
        }

        /**
         * @param removeStorages If true, remove all pveceph-managed storages configured for this pool on destroy.
         * 
         * @return builder
         * 
         */
        public Builder removeStorages(Boolean removeStorages) {
            return removeStorages(Output.of(removeStorages));
        }

        /**
         * @param size Number of replicas per object.
         * 
         * @return builder
         * 
         */
        public Builder size(@Nullable Output<Integer> size) {
            $.size = size;
            return this;
        }

        /**
         * @param size Number of replicas per object.
         * 
         * @return builder
         * 
         */
        public Builder size(Integer size) {
            return size(Output.of(size));
        }

        /**
         * @param targetSize Estimated target size for the PG autoscaler (e.g. `100G`). **Write-only:** PVE returns this as a bytes integer (e.g. &lt;span pulumi-lang-nodejs=&#34;`1073741824`&#34; pulumi-lang-dotnet=&#34;`1073741824`&#34; pulumi-lang-go=&#34;`1073741824`&#34; pulumi-lang-python=&#34;`1073741824`&#34; pulumi-lang-yaml=&#34;`1073741824`&#34; pulumi-lang-java=&#34;`1073741824`&#34; pulumi-lang-hcl=&#34;`1073741824`&#34;&gt;`1073741824`&lt;/span&gt;) while the input accepts a unit-suffixed string, so the configured spec is not round-tripped from the server.
         * 
         * @return builder
         * 
         */
        public Builder targetSize(@Nullable Output<String> targetSize) {
            $.targetSize = targetSize;
            return this;
        }

        /**
         * @param targetSize Estimated target size for the PG autoscaler (e.g. `100G`). **Write-only:** PVE returns this as a bytes integer (e.g. &lt;span pulumi-lang-nodejs=&#34;`1073741824`&#34; pulumi-lang-dotnet=&#34;`1073741824`&#34; pulumi-lang-go=&#34;`1073741824`&#34; pulumi-lang-python=&#34;`1073741824`&#34; pulumi-lang-yaml=&#34;`1073741824`&#34; pulumi-lang-java=&#34;`1073741824`&#34; pulumi-lang-hcl=&#34;`1073741824`&#34;&gt;`1073741824`&lt;/span&gt;) while the input accepts a unit-suffixed string, so the configured spec is not round-tripped from the server.
         * 
         * @return builder
         * 
         */
        public Builder targetSize(String targetSize) {
            return targetSize(Output.of(targetSize));
        }

        /**
         * @param targetSizeRatio Estimated target ratio for the PG autoscaler. **Write-only:** kept symmetric with &lt;span pulumi-lang-nodejs=&#34;`targetSize`&#34; pulumi-lang-dotnet=&#34;`TargetSize`&#34; pulumi-lang-go=&#34;`targetSize`&#34; pulumi-lang-python=&#34;`target_size`&#34; pulumi-lang-yaml=&#34;`targetSize`&#34; pulumi-lang-java=&#34;`targetSize`&#34; pulumi-lang-hcl=&#34;`target_size`&#34;&gt;`targetSize`&lt;/span&gt; (which cannot be round-tripped), so the configured value is not refreshed from the server.
         * 
         * @return builder
         * 
         */
        public Builder targetSizeRatio(@Nullable Output<Double> targetSizeRatio) {
            $.targetSizeRatio = targetSizeRatio;
            return this;
        }

        /**
         * @param targetSizeRatio Estimated target ratio for the PG autoscaler. **Write-only:** kept symmetric with &lt;span pulumi-lang-nodejs=&#34;`targetSize`&#34; pulumi-lang-dotnet=&#34;`TargetSize`&#34; pulumi-lang-go=&#34;`targetSize`&#34; pulumi-lang-python=&#34;`target_size`&#34; pulumi-lang-yaml=&#34;`targetSize`&#34; pulumi-lang-java=&#34;`targetSize`&#34; pulumi-lang-hcl=&#34;`target_size`&#34;&gt;`targetSize`&lt;/span&gt; (which cannot be round-tripped), so the configured value is not refreshed from the server.
         * 
         * @return builder
         * 
         */
        public Builder targetSizeRatio(Double targetSizeRatio) {
            return targetSizeRatio(Output.of(targetSizeRatio));
        }

        public PoolArgs build() {
            if ($.nodeName == null) {
                throw new MissingRequiredPropertyException("PoolArgs", "nodeName");
            }
            return $;
        }
    }

}
