// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.muehlbachler.pulumi.proxmoxve.cloned.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VmLegacyMemoryArgs extends com.pulumi.resources.ResourceArgs {

    public static final VmLegacyMemoryArgs Empty = new VmLegacyMemoryArgs();

    /**
     * Minimum guaranteed memory in MiB via balloon device. This is the floor amount of RAM that is always guaranteed to the VM. Setting to &lt;span pulumi-lang-nodejs=&#34;`0`&#34; pulumi-lang-dotnet=&#34;`0`&#34; pulumi-lang-go=&#34;`0`&#34; pulumi-lang-python=&#34;`0`&#34; pulumi-lang-yaml=&#34;`0`&#34; pulumi-lang-java=&#34;`0`&#34;&gt;`0`&lt;/span&gt; disables the balloon driver entirely.
     * 
     */
    @Import(name="balloon")
    private @Nullable Output<Integer> balloon;

    /**
     * @return Minimum guaranteed memory in MiB via balloon device. This is the floor amount of RAM that is always guaranteed to the VM. Setting to &lt;span pulumi-lang-nodejs=&#34;`0`&#34; pulumi-lang-dotnet=&#34;`0`&#34; pulumi-lang-go=&#34;`0`&#34; pulumi-lang-python=&#34;`0`&#34; pulumi-lang-yaml=&#34;`0`&#34; pulumi-lang-java=&#34;`0`&#34;&gt;`0`&lt;/span&gt; disables the balloon driver entirely.
     * 
     */
    public Optional<Output<Integer>> balloon() {
        return Optional.ofNullable(this.balloon);
    }

    /**
     * Enable hugepages for VM memory allocation. Hugepages can improve performance for memory-intensive workloads by reducing TLB misses.
     * 
     * **Options:**
     * - &lt;span pulumi-lang-nodejs=&#34;`2`&#34; pulumi-lang-dotnet=&#34;`2`&#34; pulumi-lang-go=&#34;`2`&#34; pulumi-lang-python=&#34;`2`&#34; pulumi-lang-yaml=&#34;`2`&#34; pulumi-lang-java=&#34;`2`&#34;&gt;`2`&lt;/span&gt; - Use 2 MiB hugepages
     * - &lt;span pulumi-lang-nodejs=&#34;`1024`&#34; pulumi-lang-dotnet=&#34;`1024`&#34; pulumi-lang-go=&#34;`1024`&#34; pulumi-lang-python=&#34;`1024`&#34; pulumi-lang-yaml=&#34;`1024`&#34; pulumi-lang-java=&#34;`1024`&#34;&gt;`1024`&lt;/span&gt; - Use 1 GiB hugepages
     * - &lt;span pulumi-lang-nodejs=&#34;`any`&#34; pulumi-lang-dotnet=&#34;`Any`&#34; pulumi-lang-go=&#34;`any`&#34; pulumi-lang-python=&#34;`any`&#34; pulumi-lang-yaml=&#34;`any`&#34; pulumi-lang-java=&#34;`any`&#34;&gt;`any`&lt;/span&gt; - Use any available hugepage size
     * 
     */
    @Import(name="hugepages")
    private @Nullable Output<String> hugepages;

    /**
     * @return Enable hugepages for VM memory allocation. Hugepages can improve performance for memory-intensive workloads by reducing TLB misses.
     * 
     * **Options:**
     * - &lt;span pulumi-lang-nodejs=&#34;`2`&#34; pulumi-lang-dotnet=&#34;`2`&#34; pulumi-lang-go=&#34;`2`&#34; pulumi-lang-python=&#34;`2`&#34; pulumi-lang-yaml=&#34;`2`&#34; pulumi-lang-java=&#34;`2`&#34;&gt;`2`&lt;/span&gt; - Use 2 MiB hugepages
     * - &lt;span pulumi-lang-nodejs=&#34;`1024`&#34; pulumi-lang-dotnet=&#34;`1024`&#34; pulumi-lang-go=&#34;`1024`&#34; pulumi-lang-python=&#34;`1024`&#34; pulumi-lang-yaml=&#34;`1024`&#34; pulumi-lang-java=&#34;`1024`&#34;&gt;`1024`&lt;/span&gt; - Use 1 GiB hugepages
     * - &lt;span pulumi-lang-nodejs=&#34;`any`&#34; pulumi-lang-dotnet=&#34;`Any`&#34; pulumi-lang-go=&#34;`any`&#34; pulumi-lang-python=&#34;`any`&#34; pulumi-lang-yaml=&#34;`any`&#34; pulumi-lang-java=&#34;`any`&#34;&gt;`any`&lt;/span&gt; - Use any available hugepage size
     * 
     */
    public Optional<Output<String>> hugepages() {
        return Optional.ofNullable(this.hugepages);
    }

    /**
     * Don&#39;t release hugepages when the VM shuts down. By default, hugepages are released back to the host when the VM stops. Setting this to &lt;span pulumi-lang-nodejs=&#34;`true`&#34; pulumi-lang-dotnet=&#34;`True`&#34; pulumi-lang-go=&#34;`true`&#34; pulumi-lang-python=&#34;`true`&#34; pulumi-lang-yaml=&#34;`true`&#34; pulumi-lang-java=&#34;`true`&#34;&gt;`true`&lt;/span&gt; keeps them allocated for faster VM startup.
     * 
     */
    @Import(name="keepHugepages")
    private @Nullable Output<Boolean> keepHugepages;

    /**
     * @return Don&#39;t release hugepages when the VM shuts down. By default, hugepages are released back to the host when the VM stops. Setting this to &lt;span pulumi-lang-nodejs=&#34;`true`&#34; pulumi-lang-dotnet=&#34;`True`&#34; pulumi-lang-go=&#34;`true`&#34; pulumi-lang-python=&#34;`true`&#34; pulumi-lang-yaml=&#34;`true`&#34; pulumi-lang-java=&#34;`true`&#34;&gt;`true`&lt;/span&gt; keeps them allocated for faster VM startup.
     * 
     */
    public Optional<Output<Boolean>> keepHugepages() {
        return Optional.ofNullable(this.keepHugepages);
    }

    /**
     * CPU scheduler priority for memory ballooning. This is used by the kernel fair scheduler. Higher values mean this VM gets more CPU time during memory ballooning operations. The value is relative to other running VMs.
     * 
     */
    @Import(name="shares")
    private @Nullable Output<Integer> shares;

    /**
     * @return CPU scheduler priority for memory ballooning. This is used by the kernel fair scheduler. Higher values mean this VM gets more CPU time during memory ballooning operations. The value is relative to other running VMs.
     * 
     */
    public Optional<Output<Integer>> shares() {
        return Optional.ofNullable(this.shares);
    }

    /**
     * Total memory available to the VM in MiB. This is the total RAM the VM can use. When ballooning is enabled (balloon &gt; 0), memory between &lt;span pulumi-lang-nodejs=&#34;`balloon`&#34; pulumi-lang-dotnet=&#34;`Balloon`&#34; pulumi-lang-go=&#34;`balloon`&#34; pulumi-lang-python=&#34;`balloon`&#34; pulumi-lang-yaml=&#34;`balloon`&#34; pulumi-lang-java=&#34;`balloon`&#34;&gt;`balloon`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`size`&#34; pulumi-lang-dotnet=&#34;`Size`&#34; pulumi-lang-go=&#34;`size`&#34; pulumi-lang-python=&#34;`size`&#34; pulumi-lang-yaml=&#34;`size`&#34; pulumi-lang-java=&#34;`size`&#34;&gt;`size`&lt;/span&gt; can be reclaimed by the host. When ballooning is disabled (balloon = 0), this is the fixed amount of RAM allocated to the VM. Defaults to PVE&#39;s implicit &lt;span pulumi-lang-nodejs=&#34;`512`&#34; pulumi-lang-dotnet=&#34;`512`&#34; pulumi-lang-go=&#34;`512`&#34; pulumi-lang-python=&#34;`512`&#34; pulumi-lang-yaml=&#34;`512`&#34; pulumi-lang-java=&#34;`512`&#34;&gt;`512`&lt;/span&gt; MiB when unset.
     * 
     */
    @Import(name="size")
    private @Nullable Output<Integer> size;

    /**
     * @return Total memory available to the VM in MiB. This is the total RAM the VM can use. When ballooning is enabled (balloon &gt; 0), memory between &lt;span pulumi-lang-nodejs=&#34;`balloon`&#34; pulumi-lang-dotnet=&#34;`Balloon`&#34; pulumi-lang-go=&#34;`balloon`&#34; pulumi-lang-python=&#34;`balloon`&#34; pulumi-lang-yaml=&#34;`balloon`&#34; pulumi-lang-java=&#34;`balloon`&#34;&gt;`balloon`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`size`&#34; pulumi-lang-dotnet=&#34;`Size`&#34; pulumi-lang-go=&#34;`size`&#34; pulumi-lang-python=&#34;`size`&#34; pulumi-lang-yaml=&#34;`size`&#34; pulumi-lang-java=&#34;`size`&#34;&gt;`size`&lt;/span&gt; can be reclaimed by the host. When ballooning is disabled (balloon = 0), this is the fixed amount of RAM allocated to the VM. Defaults to PVE&#39;s implicit &lt;span pulumi-lang-nodejs=&#34;`512`&#34; pulumi-lang-dotnet=&#34;`512`&#34; pulumi-lang-go=&#34;`512`&#34; pulumi-lang-python=&#34;`512`&#34; pulumi-lang-yaml=&#34;`512`&#34; pulumi-lang-java=&#34;`512`&#34;&gt;`512`&lt;/span&gt; MiB when unset.
     * 
     */
    public Optional<Output<Integer>> size() {
        return Optional.ofNullable(this.size);
    }

    private VmLegacyMemoryArgs() {}

    private VmLegacyMemoryArgs(VmLegacyMemoryArgs $) {
        this.balloon = $.balloon;
        this.hugepages = $.hugepages;
        this.keepHugepages = $.keepHugepages;
        this.shares = $.shares;
        this.size = $.size;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VmLegacyMemoryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VmLegacyMemoryArgs $;

        public Builder() {
            $ = new VmLegacyMemoryArgs();
        }

        public Builder(VmLegacyMemoryArgs defaults) {
            $ = new VmLegacyMemoryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param balloon Minimum guaranteed memory in MiB via balloon device. This is the floor amount of RAM that is always guaranteed to the VM. Setting to &lt;span pulumi-lang-nodejs=&#34;`0`&#34; pulumi-lang-dotnet=&#34;`0`&#34; pulumi-lang-go=&#34;`0`&#34; pulumi-lang-python=&#34;`0`&#34; pulumi-lang-yaml=&#34;`0`&#34; pulumi-lang-java=&#34;`0`&#34;&gt;`0`&lt;/span&gt; disables the balloon driver entirely.
         * 
         * @return builder
         * 
         */
        public Builder balloon(@Nullable Output<Integer> balloon) {
            $.balloon = balloon;
            return this;
        }

        /**
         * @param balloon Minimum guaranteed memory in MiB via balloon device. This is the floor amount of RAM that is always guaranteed to the VM. Setting to &lt;span pulumi-lang-nodejs=&#34;`0`&#34; pulumi-lang-dotnet=&#34;`0`&#34; pulumi-lang-go=&#34;`0`&#34; pulumi-lang-python=&#34;`0`&#34; pulumi-lang-yaml=&#34;`0`&#34; pulumi-lang-java=&#34;`0`&#34;&gt;`0`&lt;/span&gt; disables the balloon driver entirely.
         * 
         * @return builder
         * 
         */
        public Builder balloon(Integer balloon) {
            return balloon(Output.of(balloon));
        }

        /**
         * @param hugepages Enable hugepages for VM memory allocation. Hugepages can improve performance for memory-intensive workloads by reducing TLB misses.
         * 
         * **Options:**
         * - &lt;span pulumi-lang-nodejs=&#34;`2`&#34; pulumi-lang-dotnet=&#34;`2`&#34; pulumi-lang-go=&#34;`2`&#34; pulumi-lang-python=&#34;`2`&#34; pulumi-lang-yaml=&#34;`2`&#34; pulumi-lang-java=&#34;`2`&#34;&gt;`2`&lt;/span&gt; - Use 2 MiB hugepages
         * - &lt;span pulumi-lang-nodejs=&#34;`1024`&#34; pulumi-lang-dotnet=&#34;`1024`&#34; pulumi-lang-go=&#34;`1024`&#34; pulumi-lang-python=&#34;`1024`&#34; pulumi-lang-yaml=&#34;`1024`&#34; pulumi-lang-java=&#34;`1024`&#34;&gt;`1024`&lt;/span&gt; - Use 1 GiB hugepages
         * - &lt;span pulumi-lang-nodejs=&#34;`any`&#34; pulumi-lang-dotnet=&#34;`Any`&#34; pulumi-lang-go=&#34;`any`&#34; pulumi-lang-python=&#34;`any`&#34; pulumi-lang-yaml=&#34;`any`&#34; pulumi-lang-java=&#34;`any`&#34;&gt;`any`&lt;/span&gt; - Use any available hugepage size
         * 
         * @return builder
         * 
         */
        public Builder hugepages(@Nullable Output<String> hugepages) {
            $.hugepages = hugepages;
            return this;
        }

        /**
         * @param hugepages Enable hugepages for VM memory allocation. Hugepages can improve performance for memory-intensive workloads by reducing TLB misses.
         * 
         * **Options:**
         * - &lt;span pulumi-lang-nodejs=&#34;`2`&#34; pulumi-lang-dotnet=&#34;`2`&#34; pulumi-lang-go=&#34;`2`&#34; pulumi-lang-python=&#34;`2`&#34; pulumi-lang-yaml=&#34;`2`&#34; pulumi-lang-java=&#34;`2`&#34;&gt;`2`&lt;/span&gt; - Use 2 MiB hugepages
         * - &lt;span pulumi-lang-nodejs=&#34;`1024`&#34; pulumi-lang-dotnet=&#34;`1024`&#34; pulumi-lang-go=&#34;`1024`&#34; pulumi-lang-python=&#34;`1024`&#34; pulumi-lang-yaml=&#34;`1024`&#34; pulumi-lang-java=&#34;`1024`&#34;&gt;`1024`&lt;/span&gt; - Use 1 GiB hugepages
         * - &lt;span pulumi-lang-nodejs=&#34;`any`&#34; pulumi-lang-dotnet=&#34;`Any`&#34; pulumi-lang-go=&#34;`any`&#34; pulumi-lang-python=&#34;`any`&#34; pulumi-lang-yaml=&#34;`any`&#34; pulumi-lang-java=&#34;`any`&#34;&gt;`any`&lt;/span&gt; - Use any available hugepage size
         * 
         * @return builder
         * 
         */
        public Builder hugepages(String hugepages) {
            return hugepages(Output.of(hugepages));
        }

        /**
         * @param keepHugepages Don&#39;t release hugepages when the VM shuts down. By default, hugepages are released back to the host when the VM stops. Setting this to &lt;span pulumi-lang-nodejs=&#34;`true`&#34; pulumi-lang-dotnet=&#34;`True`&#34; pulumi-lang-go=&#34;`true`&#34; pulumi-lang-python=&#34;`true`&#34; pulumi-lang-yaml=&#34;`true`&#34; pulumi-lang-java=&#34;`true`&#34;&gt;`true`&lt;/span&gt; keeps them allocated for faster VM startup.
         * 
         * @return builder
         * 
         */
        public Builder keepHugepages(@Nullable Output<Boolean> keepHugepages) {
            $.keepHugepages = keepHugepages;
            return this;
        }

        /**
         * @param keepHugepages Don&#39;t release hugepages when the VM shuts down. By default, hugepages are released back to the host when the VM stops. Setting this to &lt;span pulumi-lang-nodejs=&#34;`true`&#34; pulumi-lang-dotnet=&#34;`True`&#34; pulumi-lang-go=&#34;`true`&#34; pulumi-lang-python=&#34;`true`&#34; pulumi-lang-yaml=&#34;`true`&#34; pulumi-lang-java=&#34;`true`&#34;&gt;`true`&lt;/span&gt; keeps them allocated for faster VM startup.
         * 
         * @return builder
         * 
         */
        public Builder keepHugepages(Boolean keepHugepages) {
            return keepHugepages(Output.of(keepHugepages));
        }

        /**
         * @param shares CPU scheduler priority for memory ballooning. This is used by the kernel fair scheduler. Higher values mean this VM gets more CPU time during memory ballooning operations. The value is relative to other running VMs.
         * 
         * @return builder
         * 
         */
        public Builder shares(@Nullable Output<Integer> shares) {
            $.shares = shares;
            return this;
        }

        /**
         * @param shares CPU scheduler priority for memory ballooning. This is used by the kernel fair scheduler. Higher values mean this VM gets more CPU time during memory ballooning operations. The value is relative to other running VMs.
         * 
         * @return builder
         * 
         */
        public Builder shares(Integer shares) {
            return shares(Output.of(shares));
        }

        /**
         * @param size Total memory available to the VM in MiB. This is the total RAM the VM can use. When ballooning is enabled (balloon &gt; 0), memory between &lt;span pulumi-lang-nodejs=&#34;`balloon`&#34; pulumi-lang-dotnet=&#34;`Balloon`&#34; pulumi-lang-go=&#34;`balloon`&#34; pulumi-lang-python=&#34;`balloon`&#34; pulumi-lang-yaml=&#34;`balloon`&#34; pulumi-lang-java=&#34;`balloon`&#34;&gt;`balloon`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`size`&#34; pulumi-lang-dotnet=&#34;`Size`&#34; pulumi-lang-go=&#34;`size`&#34; pulumi-lang-python=&#34;`size`&#34; pulumi-lang-yaml=&#34;`size`&#34; pulumi-lang-java=&#34;`size`&#34;&gt;`size`&lt;/span&gt; can be reclaimed by the host. When ballooning is disabled (balloon = 0), this is the fixed amount of RAM allocated to the VM. Defaults to PVE&#39;s implicit &lt;span pulumi-lang-nodejs=&#34;`512`&#34; pulumi-lang-dotnet=&#34;`512`&#34; pulumi-lang-go=&#34;`512`&#34; pulumi-lang-python=&#34;`512`&#34; pulumi-lang-yaml=&#34;`512`&#34; pulumi-lang-java=&#34;`512`&#34;&gt;`512`&lt;/span&gt; MiB when unset.
         * 
         * @return builder
         * 
         */
        public Builder size(@Nullable Output<Integer> size) {
            $.size = size;
            return this;
        }

        /**
         * @param size Total memory available to the VM in MiB. This is the total RAM the VM can use. When ballooning is enabled (balloon &gt; 0), memory between &lt;span pulumi-lang-nodejs=&#34;`balloon`&#34; pulumi-lang-dotnet=&#34;`Balloon`&#34; pulumi-lang-go=&#34;`balloon`&#34; pulumi-lang-python=&#34;`balloon`&#34; pulumi-lang-yaml=&#34;`balloon`&#34; pulumi-lang-java=&#34;`balloon`&#34;&gt;`balloon`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`size`&#34; pulumi-lang-dotnet=&#34;`Size`&#34; pulumi-lang-go=&#34;`size`&#34; pulumi-lang-python=&#34;`size`&#34; pulumi-lang-yaml=&#34;`size`&#34; pulumi-lang-java=&#34;`size`&#34;&gt;`size`&lt;/span&gt; can be reclaimed by the host. When ballooning is disabled (balloon = 0), this is the fixed amount of RAM allocated to the VM. Defaults to PVE&#39;s implicit &lt;span pulumi-lang-nodejs=&#34;`512`&#34; pulumi-lang-dotnet=&#34;`512`&#34; pulumi-lang-go=&#34;`512`&#34; pulumi-lang-python=&#34;`512`&#34; pulumi-lang-yaml=&#34;`512`&#34; pulumi-lang-java=&#34;`512`&#34;&gt;`512`&lt;/span&gt; MiB when unset.
         * 
         * @return builder
         * 
         */
        public Builder size(Integer size) {
            return size(Output.of(size));
        }

        public VmLegacyMemoryArgs build() {
            return $;
        }
    }

}
