// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package node

import (
	"context"
	"reflect"

	"github.com/muhlba91/pulumi-proxmoxve/sdk/v7/go/proxmoxve/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// > **Deprecated:** Use `sdn/fabric/node.Openfabric` instead. This data source will be removed in v1.0.
//
// OpenFabric Fabric Node in Proxmox SDN. Fabrics in Proxmox VE SDN provide automated routing between nodes in a cluster.
func LookupOpenfabricLegacy(ctx *pulumi.Context, args *LookupOpenfabricLegacyArgs, opts ...pulumi.InvokeOption) (*LookupOpenfabricLegacyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOpenfabricLegacyResult
	err := ctx.Invoke("proxmoxve:sdn/fabric/node/getOpenfabricLegacy:getOpenfabricLegacy", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOpenfabricLegacy.
type LookupOpenfabricLegacyArgs struct {
	// The unique identifier of the SDN fabric.
	FabricId string `pulumi:"fabricId"`
	// The unique identifier of the SDN fabric node.
	NodeId string `pulumi:"nodeId"`
}

// A collection of values returned by getOpenfabricLegacy.
type LookupOpenfabricLegacyResult struct {
	// The unique identifier of the SDN fabric.
	FabricId string `pulumi:"fabricId"`
	// The unique identifier of the SDN fabric node, in the format \n\n/\n\n.
	Id string `pulumi:"id"`
	// Set of interface names associated with the fabric node.
	InterfaceNames []string `pulumi:"interfaceNames"`
	// IPv4 address for the fabric node.
	Ip string `pulumi:"ip"`
	// IPv6 address for the fabric node.
	Ip6 string `pulumi:"ip6"`
	// The unique identifier of the SDN fabric node.
	NodeId string `pulumi:"nodeId"`
}

func LookupOpenfabricLegacyOutput(ctx *pulumi.Context, args LookupOpenfabricLegacyOutputArgs, opts ...pulumi.InvokeOption) LookupOpenfabricLegacyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupOpenfabricLegacyResultOutput, error) {
			args := v.(LookupOpenfabricLegacyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("proxmoxve:sdn/fabric/node/getOpenfabricLegacy:getOpenfabricLegacy", args, LookupOpenfabricLegacyResultOutput{}, options).(LookupOpenfabricLegacyResultOutput), nil
		}).(LookupOpenfabricLegacyResultOutput)
}

// A collection of arguments for invoking getOpenfabricLegacy.
type LookupOpenfabricLegacyOutputArgs struct {
	// The unique identifier of the SDN fabric.
	FabricId pulumi.StringInput `pulumi:"fabricId"`
	// The unique identifier of the SDN fabric node.
	NodeId pulumi.StringInput `pulumi:"nodeId"`
}

func (LookupOpenfabricLegacyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOpenfabricLegacyArgs)(nil)).Elem()
}

// A collection of values returned by getOpenfabricLegacy.
type LookupOpenfabricLegacyResultOutput struct{ *pulumi.OutputState }

func (LookupOpenfabricLegacyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOpenfabricLegacyResult)(nil)).Elem()
}

func (o LookupOpenfabricLegacyResultOutput) ToLookupOpenfabricLegacyResultOutput() LookupOpenfabricLegacyResultOutput {
	return o
}

func (o LookupOpenfabricLegacyResultOutput) ToLookupOpenfabricLegacyResultOutputWithContext(ctx context.Context) LookupOpenfabricLegacyResultOutput {
	return o
}

// The unique identifier of the SDN fabric.
func (o LookupOpenfabricLegacyResultOutput) FabricId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOpenfabricLegacyResult) string { return v.FabricId }).(pulumi.StringOutput)
}

// The unique identifier of the SDN fabric node, in the format \n\n/\n\n.
func (o LookupOpenfabricLegacyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOpenfabricLegacyResult) string { return v.Id }).(pulumi.StringOutput)
}

// Set of interface names associated with the fabric node.
func (o LookupOpenfabricLegacyResultOutput) InterfaceNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupOpenfabricLegacyResult) []string { return v.InterfaceNames }).(pulumi.StringArrayOutput)
}

// IPv4 address for the fabric node.
func (o LookupOpenfabricLegacyResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOpenfabricLegacyResult) string { return v.Ip }).(pulumi.StringOutput)
}

// IPv6 address for the fabric node.
func (o LookupOpenfabricLegacyResultOutput) Ip6() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOpenfabricLegacyResult) string { return v.Ip6 }).(pulumi.StringOutput)
}

// The unique identifier of the SDN fabric node.
func (o LookupOpenfabricLegacyResultOutput) NodeId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOpenfabricLegacyResult) string { return v.NodeId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOpenfabricLegacyResultOutput{})
}
