// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package node

import (
	"context"
	"reflect"

	"errors"
	"github.com/muhlba91/pulumi-proxmoxve/sdk/v8/go/proxmoxve/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// > **Deprecated:** Use `sdn/fabric/node.Ospf` instead. This resource will be removed in v1.0.
//
// OSPF Fabric Node in Proxmox SDN. Fabrics in Proxmox VE SDN provide automated routing between nodes in a cluster.
type OspfLegacy struct {
	pulumi.CustomResourceState

	// The unique identifier of the SDN fabric.
	FabricId pulumi.StringOutput `pulumi:"fabricId"`
	// Set of interfaces associated with the fabric node.
	InterfaceNames pulumi.StringArrayOutput `pulumi:"interfaceNames"`
	// IPv4 address for the fabric node.
	Ip pulumi.StringOutput `pulumi:"ip"`
	// The unique identifier of the SDN fabric node.
	NodeId pulumi.StringOutput `pulumi:"nodeId"`
}

// NewOspfLegacy registers a new resource with the given unique name, arguments, and options.
func NewOspfLegacy(ctx *pulumi.Context,
	name string, args *OspfLegacyArgs, opts ...pulumi.ResourceOption) (*OspfLegacy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.FabricId == nil {
		return nil, errors.New("invalid value for required argument 'FabricId'")
	}
	if args.InterfaceNames == nil {
		return nil, errors.New("invalid value for required argument 'InterfaceNames'")
	}
	if args.Ip == nil {
		return nil, errors.New("invalid value for required argument 'Ip'")
	}
	if args.NodeId == nil {
		return nil, errors.New("invalid value for required argument 'NodeId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OspfLegacy
	err := ctx.RegisterResource("proxmoxve:sdn/fabric/node/ospfLegacy:OspfLegacy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOspfLegacy gets an existing OspfLegacy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOspfLegacy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OspfLegacyState, opts ...pulumi.ResourceOption) (*OspfLegacy, error) {
	var resource OspfLegacy
	err := ctx.ReadResource("proxmoxve:sdn/fabric/node/ospfLegacy:OspfLegacy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OspfLegacy resources.
type ospfLegacyState struct {
	// The unique identifier of the SDN fabric.
	FabricId *string `pulumi:"fabricId"`
	// Set of interfaces associated with the fabric node.
	InterfaceNames []string `pulumi:"interfaceNames"`
	// IPv4 address for the fabric node.
	Ip *string `pulumi:"ip"`
	// The unique identifier of the SDN fabric node.
	NodeId *string `pulumi:"nodeId"`
}

type OspfLegacyState struct {
	// The unique identifier of the SDN fabric.
	FabricId pulumi.StringPtrInput
	// Set of interfaces associated with the fabric node.
	InterfaceNames pulumi.StringArrayInput
	// IPv4 address for the fabric node.
	Ip pulumi.StringPtrInput
	// The unique identifier of the SDN fabric node.
	NodeId pulumi.StringPtrInput
}

func (OspfLegacyState) ElementType() reflect.Type {
	return reflect.TypeOf((*ospfLegacyState)(nil)).Elem()
}

type ospfLegacyArgs struct {
	// The unique identifier of the SDN fabric.
	FabricId string `pulumi:"fabricId"`
	// Set of interfaces associated with the fabric node.
	InterfaceNames []string `pulumi:"interfaceNames"`
	// IPv4 address for the fabric node.
	Ip string `pulumi:"ip"`
	// The unique identifier of the SDN fabric node.
	NodeId string `pulumi:"nodeId"`
}

// The set of arguments for constructing a OspfLegacy resource.
type OspfLegacyArgs struct {
	// The unique identifier of the SDN fabric.
	FabricId pulumi.StringInput
	// Set of interfaces associated with the fabric node.
	InterfaceNames pulumi.StringArrayInput
	// IPv4 address for the fabric node.
	Ip pulumi.StringInput
	// The unique identifier of the SDN fabric node.
	NodeId pulumi.StringInput
}

func (OspfLegacyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ospfLegacyArgs)(nil)).Elem()
}

type OspfLegacyInput interface {
	pulumi.Input

	ToOspfLegacyOutput() OspfLegacyOutput
	ToOspfLegacyOutputWithContext(ctx context.Context) OspfLegacyOutput
}

func (*OspfLegacy) ElementType() reflect.Type {
	return reflect.TypeOf((**OspfLegacy)(nil)).Elem()
}

func (i *OspfLegacy) ToOspfLegacyOutput() OspfLegacyOutput {
	return i.ToOspfLegacyOutputWithContext(context.Background())
}

func (i *OspfLegacy) ToOspfLegacyOutputWithContext(ctx context.Context) OspfLegacyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OspfLegacyOutput)
}

// OspfLegacyArrayInput is an input type that accepts OspfLegacyArray and OspfLegacyArrayOutput values.
// You can construct a concrete instance of `OspfLegacyArrayInput` via:
//
//	OspfLegacyArray{ OspfLegacyArgs{...} }
type OspfLegacyArrayInput interface {
	pulumi.Input

	ToOspfLegacyArrayOutput() OspfLegacyArrayOutput
	ToOspfLegacyArrayOutputWithContext(context.Context) OspfLegacyArrayOutput
}

type OspfLegacyArray []OspfLegacyInput

func (OspfLegacyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OspfLegacy)(nil)).Elem()
}

func (i OspfLegacyArray) ToOspfLegacyArrayOutput() OspfLegacyArrayOutput {
	return i.ToOspfLegacyArrayOutputWithContext(context.Background())
}

func (i OspfLegacyArray) ToOspfLegacyArrayOutputWithContext(ctx context.Context) OspfLegacyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OspfLegacyArrayOutput)
}

// OspfLegacyMapInput is an input type that accepts OspfLegacyMap and OspfLegacyMapOutput values.
// You can construct a concrete instance of `OspfLegacyMapInput` via:
//
//	OspfLegacyMap{ "key": OspfLegacyArgs{...} }
type OspfLegacyMapInput interface {
	pulumi.Input

	ToOspfLegacyMapOutput() OspfLegacyMapOutput
	ToOspfLegacyMapOutputWithContext(context.Context) OspfLegacyMapOutput
}

type OspfLegacyMap map[string]OspfLegacyInput

func (OspfLegacyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OspfLegacy)(nil)).Elem()
}

func (i OspfLegacyMap) ToOspfLegacyMapOutput() OspfLegacyMapOutput {
	return i.ToOspfLegacyMapOutputWithContext(context.Background())
}

func (i OspfLegacyMap) ToOspfLegacyMapOutputWithContext(ctx context.Context) OspfLegacyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OspfLegacyMapOutput)
}

type OspfLegacyOutput struct{ *pulumi.OutputState }

func (OspfLegacyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OspfLegacy)(nil)).Elem()
}

func (o OspfLegacyOutput) ToOspfLegacyOutput() OspfLegacyOutput {
	return o
}

func (o OspfLegacyOutput) ToOspfLegacyOutputWithContext(ctx context.Context) OspfLegacyOutput {
	return o
}

// The unique identifier of the SDN fabric.
func (o OspfLegacyOutput) FabricId() pulumi.StringOutput {
	return o.ApplyT(func(v *OspfLegacy) pulumi.StringOutput { return v.FabricId }).(pulumi.StringOutput)
}

// Set of interfaces associated with the fabric node.
func (o OspfLegacyOutput) InterfaceNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *OspfLegacy) pulumi.StringArrayOutput { return v.InterfaceNames }).(pulumi.StringArrayOutput)
}

// IPv4 address for the fabric node.
func (o OspfLegacyOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v *OspfLegacy) pulumi.StringOutput { return v.Ip }).(pulumi.StringOutput)
}

// The unique identifier of the SDN fabric node.
func (o OspfLegacyOutput) NodeId() pulumi.StringOutput {
	return o.ApplyT(func(v *OspfLegacy) pulumi.StringOutput { return v.NodeId }).(pulumi.StringOutput)
}

type OspfLegacyArrayOutput struct{ *pulumi.OutputState }

func (OspfLegacyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OspfLegacy)(nil)).Elem()
}

func (o OspfLegacyArrayOutput) ToOspfLegacyArrayOutput() OspfLegacyArrayOutput {
	return o
}

func (o OspfLegacyArrayOutput) ToOspfLegacyArrayOutputWithContext(ctx context.Context) OspfLegacyArrayOutput {
	return o
}

func (o OspfLegacyArrayOutput) Index(i pulumi.IntInput) OspfLegacyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *OspfLegacy {
		return vs[0].([]*OspfLegacy)[vs[1].(int)]
	}).(OspfLegacyOutput)
}

type OspfLegacyMapOutput struct{ *pulumi.OutputState }

func (OspfLegacyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OspfLegacy)(nil)).Elem()
}

func (o OspfLegacyMapOutput) ToOspfLegacyMapOutput() OspfLegacyMapOutput {
	return o
}

func (o OspfLegacyMapOutput) ToOspfLegacyMapOutputWithContext(ctx context.Context) OspfLegacyMapOutput {
	return o
}

func (o OspfLegacyMapOutput) MapIndex(k pulumi.StringInput) OspfLegacyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *OspfLegacy {
		return vs[0].(map[string]*OspfLegacy)[vs[1].(string)]
	}).(OspfLegacyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OspfLegacyInput)(nil)).Elem(), &OspfLegacy{})
	pulumi.RegisterInputType(reflect.TypeOf((*OspfLegacyArrayInput)(nil)).Elem(), OspfLegacyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OspfLegacyMapInput)(nil)).Elem(), OspfLegacyMap{})
	pulumi.RegisterOutputType(OspfLegacyOutput{})
	pulumi.RegisterOutputType(OspfLegacyArrayOutput{})
	pulumi.RegisterOutputType(OspfLegacyMapOutput{})
}
