// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.muehlbachler.pulumi.proxmoxve.Sdn_fabric_node.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetOpenfabricPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetOpenfabricPlainArgs Empty = new GetOpenfabricPlainArgs();

    /**
     * The unique identifier of the SDN fabric.
     * 
     */
    @Import(name="fabricId", required=true)
    private String fabricId;

    /**
     * @return The unique identifier of the SDN fabric.
     * 
     */
    public String fabricId() {
        return this.fabricId;
    }

    /**
     * The unique identifier of the SDN fabric node.
     * 
     */
    @Import(name="nodeId", required=true)
    private String nodeId;

    /**
     * @return The unique identifier of the SDN fabric node.
     * 
     */
    public String nodeId() {
        return this.nodeId;
    }

    private GetOpenfabricPlainArgs() {}

    private GetOpenfabricPlainArgs(GetOpenfabricPlainArgs $) {
        this.fabricId = $.fabricId;
        this.nodeId = $.nodeId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetOpenfabricPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetOpenfabricPlainArgs $;

        public Builder() {
            $ = new GetOpenfabricPlainArgs();
        }

        public Builder(GetOpenfabricPlainArgs defaults) {
            $ = new GetOpenfabricPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param fabricId The unique identifier of the SDN fabric.
         * 
         * @return builder
         * 
         */
        public Builder fabricId(String fabricId) {
            $.fabricId = fabricId;
            return this;
        }

        /**
         * @param nodeId The unique identifier of the SDN fabric node.
         * 
         * @return builder
         * 
         */
        public Builder nodeId(String nodeId) {
            $.nodeId = nodeId;
            return this;
        }

        public GetOpenfabricPlainArgs build() {
            if ($.fabricId == null) {
                throw new MissingRequiredPropertyException("GetOpenfabricPlainArgs", "fabricId");
            }
            if ($.nodeId == null) {
                throw new MissingRequiredPropertyException("GetOpenfabricPlainArgs", "nodeId");
            }
            return $;
        }
    }

}
