// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.muehlbachler.pulumi.proxmoxve.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.muehlbachler.pulumi.proxmoxve.inputs.ContainerLegacyInitializationIpConfigIpv4Args;
import io.muehlbachler.pulumi.proxmoxve.inputs.ContainerLegacyInitializationIpConfigIpv6Args;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContainerLegacyInitializationIpConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContainerLegacyInitializationIpConfigArgs Empty = new ContainerLegacyInitializationIpConfigArgs();

    /**
     * The IPv4 configuration.
     * 
     */
    @Import(name="ipv4")
    private @Nullable Output<ContainerLegacyInitializationIpConfigIpv4Args> ipv4;

    /**
     * @return The IPv4 configuration.
     * 
     */
    public Optional<Output<ContainerLegacyInitializationIpConfigIpv4Args>> ipv4() {
        return Optional.ofNullable(this.ipv4);
    }

    /**
     * The IPv6 configuration.
     * 
     */
    @Import(name="ipv6")
    private @Nullable Output<ContainerLegacyInitializationIpConfigIpv6Args> ipv6;

    /**
     * @return The IPv6 configuration.
     * 
     */
    public Optional<Output<ContainerLegacyInitializationIpConfigIpv6Args>> ipv6() {
        return Optional.ofNullable(this.ipv6);
    }

    private ContainerLegacyInitializationIpConfigArgs() {}

    private ContainerLegacyInitializationIpConfigArgs(ContainerLegacyInitializationIpConfigArgs $) {
        this.ipv4 = $.ipv4;
        this.ipv6 = $.ipv6;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContainerLegacyInitializationIpConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContainerLegacyInitializationIpConfigArgs $;

        public Builder() {
            $ = new ContainerLegacyInitializationIpConfigArgs();
        }

        public Builder(ContainerLegacyInitializationIpConfigArgs defaults) {
            $ = new ContainerLegacyInitializationIpConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param ipv4 The IPv4 configuration.
         * 
         * @return builder
         * 
         */
        public Builder ipv4(@Nullable Output<ContainerLegacyInitializationIpConfigIpv4Args> ipv4) {
            $.ipv4 = ipv4;
            return this;
        }

        /**
         * @param ipv4 The IPv4 configuration.
         * 
         * @return builder
         * 
         */
        public Builder ipv4(ContainerLegacyInitializationIpConfigIpv4Args ipv4) {
            return ipv4(Output.of(ipv4));
        }

        /**
         * @param ipv6 The IPv6 configuration.
         * 
         * @return builder
         * 
         */
        public Builder ipv6(@Nullable Output<ContainerLegacyInitializationIpConfigIpv6Args> ipv6) {
            $.ipv6 = ipv6;
            return this;
        }

        /**
         * @param ipv6 The IPv6 configuration.
         * 
         * @return builder
         * 
         */
        public Builder ipv6(ContainerLegacyInitializationIpConfigIpv6Args ipv6) {
            return ipv6(Output.of(ipv6));
        }

        public ContainerLegacyInitializationIpConfigArgs build() {
            return $;
        }
    }

}
