// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.muehlbachler.pulumi.proxmoxve.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetGroupLegacyArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetGroupLegacyArgs Empty = new GetGroupLegacyArgs();

    /**
     * The group identifier.
     * 
     */
    @Import(name="groupId", required=true)
    private Output<String> groupId;

    /**
     * @return The group identifier.
     * 
     */
    public Output<String> groupId() {
        return this.groupId;
    }

    private GetGroupLegacyArgs() {}

    private GetGroupLegacyArgs(GetGroupLegacyArgs $) {
        this.groupId = $.groupId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetGroupLegacyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetGroupLegacyArgs $;

        public Builder() {
            $ = new GetGroupLegacyArgs();
        }

        public Builder(GetGroupLegacyArgs defaults) {
            $ = new GetGroupLegacyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param groupId The group identifier.
         * 
         * @return builder
         * 
         */
        public Builder groupId(Output<String> groupId) {
            $.groupId = groupId;
            return this;
        }

        /**
         * @param groupId The group identifier.
         * 
         * @return builder
         * 
         */
        public Builder groupId(String groupId) {
            return groupId(Output.of(groupId));
        }

        public GetGroupLegacyArgs build() {
            if ($.groupId == null) {
                throw new MissingRequiredPropertyException("GetGroupLegacyArgs", "groupId");
            }
            return $;
        }
    }

}
