// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.muehlbachler.pulumi.proxmoxve.CT.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContainerConsoleArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContainerConsoleArgs Empty = new ContainerConsoleArgs();

    /**
     * Whether to enable the network device (defaults
     * to `true`).
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Whether to enable the network device (defaults
     * to `true`).
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * The number of available TTY (defaults to `2`).
     * 
     */
    @Import(name="ttyCount")
    private @Nullable Output<Integer> ttyCount;

    /**
     * @return The number of available TTY (defaults to `2`).
     * 
     */
    public Optional<Output<Integer>> ttyCount() {
        return Optional.ofNullable(this.ttyCount);
    }

    /**
     * The type (defaults to `unmanaged`).
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return The type (defaults to `unmanaged`).
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private ContainerConsoleArgs() {}

    private ContainerConsoleArgs(ContainerConsoleArgs $) {
        this.enabled = $.enabled;
        this.ttyCount = $.ttyCount;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContainerConsoleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContainerConsoleArgs $;

        public Builder() {
            $ = new ContainerConsoleArgs();
        }

        public Builder(ContainerConsoleArgs defaults) {
            $ = new ContainerConsoleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Whether to enable the network device (defaults
         * to `true`).
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether to enable the network device (defaults
         * to `true`).
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param ttyCount The number of available TTY (defaults to `2`).
         * 
         * @return builder
         * 
         */
        public Builder ttyCount(@Nullable Output<Integer> ttyCount) {
            $.ttyCount = ttyCount;
            return this;
        }

        /**
         * @param ttyCount The number of available TTY (defaults to `2`).
         * 
         * @return builder
         * 
         */
        public Builder ttyCount(Integer ttyCount) {
            return ttyCount(Output.of(ttyCount));
        }

        /**
         * @param type The type (defaults to `unmanaged`).
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The type (defaults to `unmanaged`).
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ContainerConsoleArgs build() {
            return $;
        }
    }

}
