// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * ## Import
 *
 * #!/usr/bin/env sh
 *
 * LDAP realms can be imported using the realm identifier, e.g.:
 *
 * ```sh
 * $ pulumi import proxmoxve:Realm/ldap:Ldap example example.com
 * ```
 *
 * -> When importing, the `bind_password` attribute cannot be imported since it's not returned by the Proxmox API. You'll need to set this attribute in your Terraform configuration after the import to manage it with Terraform.
 */
export class Ldap extends pulumi.CustomResource {
    /**
     * Get an existing Ldap resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LdapState, opts?: pulumi.CustomResourceOptions): Ldap {
        return new Ldap(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'proxmoxve:Realm/ldap:Ldap';

    /**
     * Returns true if the given object is an instance of Ldap.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ldap {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ldap.__pulumiType;
    }

    /**
     * LDAP base DN for user searches (e.g., 'ou=users,dc=example,dc=com').
     */
    declare public readonly baseDn: pulumi.Output<string>;
    /**
     * LDAP bind DN for authentication (e.g., 'cn=admin,dc=example,dc=com').
     */
    declare public readonly bindDn: pulumi.Output<string | undefined>;
    /**
     * Password for the bind DN. Note: stored in Proxmox but not returned by API.
     */
    declare public readonly bindPassword: pulumi.Output<string | undefined>;
    /**
     * Path to CA certificate file for SSL verification.
     */
    declare public readonly caPath: pulumi.Output<string | undefined>;
    /**
     * Enable case-sensitive username matching.
     */
    declare public readonly caseSensitive: pulumi.Output<boolean>;
    /**
     * Path to client certificate key.
     */
    declare public readonly certKeyPath: pulumi.Output<string | undefined>;
    /**
     * Path to client certificate for SSL authentication.
     */
    declare public readonly certPath: pulumi.Output<string | undefined>;
    /**
     * Description of the realm.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * Use this realm as the default for login.
     */
    declare public readonly default: pulumi.Output<boolean>;
    /**
     * LDAP filter for user searches.
     */
    declare public readonly filter: pulumi.Output<string | undefined>;
    /**
     * LDAP objectClasses for groups (comma-separated).
     */
    declare public readonly groupClasses: pulumi.Output<string | undefined>;
    /**
     * LDAP base DN for group searches.
     */
    declare public readonly groupDn: pulumi.Output<string | undefined>;
    /**
     * LDAP filter for group searches.
     */
    declare public readonly groupFilter: pulumi.Output<string | undefined>;
    /**
     * LDAP attribute representing the group name.
     */
    declare public readonly groupNameAttr: pulumi.Output<string | undefined>;
    /**
     * LDAP connection mode (ldap, ldaps, ldap+starttls).
     */
    declare public readonly mode: pulumi.Output<string | undefined>;
    /**
     * LDAP server port. Default: 389 (LDAP) or 636 (LDAPS).
     */
    declare public readonly port: pulumi.Output<number | undefined>;
    /**
     * Realm identifier (e.g., 'example.com').
     */
    declare public readonly realm: pulumi.Output<string>;
    /**
     * Use LDAPS (LDAP over SSL/TLS) instead of plain LDAP.
     *
     * @deprecated Deprecated by Proxmox: use mode instead.
     */
    declare public readonly secure: pulumi.Output<boolean>;
    /**
     * Primary LDAP server hostname or IP address.
     */
    declare public readonly server1: pulumi.Output<string>;
    /**
     * Fallback LDAP server hostname or IP address.
     */
    declare public readonly server2: pulumi.Output<string | undefined>;
    /**
     * SSL/TLS version (tlsv1, tlsv1*1, tlsv1*2, tlsv1_3).
     */
    declare public readonly sslVersion: pulumi.Output<string | undefined>;
    /**
     * Comma-separated list of attributes to sync (e.g., 'email=mail,firstname=givenName').
     */
    declare public readonly syncAttributes: pulumi.Output<string | undefined>;
    /**
     * Default synchronization options. Format: comma-separated 'key=value' pairs. Valid keys: 'scope' (users/groups/both), 'enable-new' (1/0), 'remove-vanished' (semicolon-separated: entry/acl/properties), 'full' (deprecated), 'purge' (deprecated). Example: 'scope=users,enable-new=1,remove-vanished=entry;acl'.
     */
    declare public readonly syncDefaultsOptions: pulumi.Output<string | undefined>;
    /**
     * LDAP attribute representing the username.
     */
    declare public readonly userAttr: pulumi.Output<string>;
    /**
     * LDAP objectClasses for users (comma-separated).
     */
    declare public readonly userClasses: pulumi.Output<string | undefined>;
    /**
     * Verify LDAP server SSL certificate.
     */
    declare public readonly verify: pulumi.Output<boolean>;

    /**
     * Create a Ldap resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LdapArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LdapArgs | LdapState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LdapState | undefined;
            resourceInputs["baseDn"] = state?.baseDn;
            resourceInputs["bindDn"] = state?.bindDn;
            resourceInputs["bindPassword"] = state?.bindPassword;
            resourceInputs["caPath"] = state?.caPath;
            resourceInputs["caseSensitive"] = state?.caseSensitive;
            resourceInputs["certKeyPath"] = state?.certKeyPath;
            resourceInputs["certPath"] = state?.certPath;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["default"] = state?.default;
            resourceInputs["filter"] = state?.filter;
            resourceInputs["groupClasses"] = state?.groupClasses;
            resourceInputs["groupDn"] = state?.groupDn;
            resourceInputs["groupFilter"] = state?.groupFilter;
            resourceInputs["groupNameAttr"] = state?.groupNameAttr;
            resourceInputs["mode"] = state?.mode;
            resourceInputs["port"] = state?.port;
            resourceInputs["realm"] = state?.realm;
            resourceInputs["secure"] = state?.secure;
            resourceInputs["server1"] = state?.server1;
            resourceInputs["server2"] = state?.server2;
            resourceInputs["sslVersion"] = state?.sslVersion;
            resourceInputs["syncAttributes"] = state?.syncAttributes;
            resourceInputs["syncDefaultsOptions"] = state?.syncDefaultsOptions;
            resourceInputs["userAttr"] = state?.userAttr;
            resourceInputs["userClasses"] = state?.userClasses;
            resourceInputs["verify"] = state?.verify;
        } else {
            const args = argsOrState as LdapArgs | undefined;
            if (args?.baseDn === undefined && !opts.urn) {
                throw new Error("Missing required property 'baseDn'");
            }
            if (args?.realm === undefined && !opts.urn) {
                throw new Error("Missing required property 'realm'");
            }
            if (args?.server1 === undefined && !opts.urn) {
                throw new Error("Missing required property 'server1'");
            }
            resourceInputs["baseDn"] = args?.baseDn;
            resourceInputs["bindDn"] = args?.bindDn;
            resourceInputs["bindPassword"] = args?.bindPassword ? pulumi.secret(args.bindPassword) : undefined;
            resourceInputs["caPath"] = args?.caPath;
            resourceInputs["caseSensitive"] = args?.caseSensitive;
            resourceInputs["certKeyPath"] = args?.certKeyPath;
            resourceInputs["certPath"] = args?.certPath;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["default"] = args?.default;
            resourceInputs["filter"] = args?.filter;
            resourceInputs["groupClasses"] = args?.groupClasses;
            resourceInputs["groupDn"] = args?.groupDn;
            resourceInputs["groupFilter"] = args?.groupFilter;
            resourceInputs["groupNameAttr"] = args?.groupNameAttr;
            resourceInputs["mode"] = args?.mode;
            resourceInputs["port"] = args?.port;
            resourceInputs["realm"] = args?.realm;
            resourceInputs["secure"] = args?.secure;
            resourceInputs["server1"] = args?.server1;
            resourceInputs["server2"] = args?.server2;
            resourceInputs["sslVersion"] = args?.sslVersion;
            resourceInputs["syncAttributes"] = args?.syncAttributes;
            resourceInputs["syncDefaultsOptions"] = args?.syncDefaultsOptions;
            resourceInputs["userAttr"] = args?.userAttr;
            resourceInputs["userClasses"] = args?.userClasses;
            resourceInputs["verify"] = args?.verify;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["bindPassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Ldap.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Ldap resources.
 */
export interface LdapState {
    /**
     * LDAP base DN for user searches (e.g., 'ou=users,dc=example,dc=com').
     */
    baseDn?: pulumi.Input<string>;
    /**
     * LDAP bind DN for authentication (e.g., 'cn=admin,dc=example,dc=com').
     */
    bindDn?: pulumi.Input<string>;
    /**
     * Password for the bind DN. Note: stored in Proxmox but not returned by API.
     */
    bindPassword?: pulumi.Input<string>;
    /**
     * Path to CA certificate file for SSL verification.
     */
    caPath?: pulumi.Input<string>;
    /**
     * Enable case-sensitive username matching.
     */
    caseSensitive?: pulumi.Input<boolean>;
    /**
     * Path to client certificate key.
     */
    certKeyPath?: pulumi.Input<string>;
    /**
     * Path to client certificate for SSL authentication.
     */
    certPath?: pulumi.Input<string>;
    /**
     * Description of the realm.
     */
    comment?: pulumi.Input<string>;
    /**
     * Use this realm as the default for login.
     */
    default?: pulumi.Input<boolean>;
    /**
     * LDAP filter for user searches.
     */
    filter?: pulumi.Input<string>;
    /**
     * LDAP objectClasses for groups (comma-separated).
     */
    groupClasses?: pulumi.Input<string>;
    /**
     * LDAP base DN for group searches.
     */
    groupDn?: pulumi.Input<string>;
    /**
     * LDAP filter for group searches.
     */
    groupFilter?: pulumi.Input<string>;
    /**
     * LDAP attribute representing the group name.
     */
    groupNameAttr?: pulumi.Input<string>;
    /**
     * LDAP connection mode (ldap, ldaps, ldap+starttls).
     */
    mode?: pulumi.Input<string>;
    /**
     * LDAP server port. Default: 389 (LDAP) or 636 (LDAPS).
     */
    port?: pulumi.Input<number>;
    /**
     * Realm identifier (e.g., 'example.com').
     */
    realm?: pulumi.Input<string>;
    /**
     * Use LDAPS (LDAP over SSL/TLS) instead of plain LDAP.
     *
     * @deprecated Deprecated by Proxmox: use mode instead.
     */
    secure?: pulumi.Input<boolean>;
    /**
     * Primary LDAP server hostname or IP address.
     */
    server1?: pulumi.Input<string>;
    /**
     * Fallback LDAP server hostname or IP address.
     */
    server2?: pulumi.Input<string>;
    /**
     * SSL/TLS version (tlsv1, tlsv1*1, tlsv1*2, tlsv1_3).
     */
    sslVersion?: pulumi.Input<string>;
    /**
     * Comma-separated list of attributes to sync (e.g., 'email=mail,firstname=givenName').
     */
    syncAttributes?: pulumi.Input<string>;
    /**
     * Default synchronization options. Format: comma-separated 'key=value' pairs. Valid keys: 'scope' (users/groups/both), 'enable-new' (1/0), 'remove-vanished' (semicolon-separated: entry/acl/properties), 'full' (deprecated), 'purge' (deprecated). Example: 'scope=users,enable-new=1,remove-vanished=entry;acl'.
     */
    syncDefaultsOptions?: pulumi.Input<string>;
    /**
     * LDAP attribute representing the username.
     */
    userAttr?: pulumi.Input<string>;
    /**
     * LDAP objectClasses for users (comma-separated).
     */
    userClasses?: pulumi.Input<string>;
    /**
     * Verify LDAP server SSL certificate.
     */
    verify?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Ldap resource.
 */
export interface LdapArgs {
    /**
     * LDAP base DN for user searches (e.g., 'ou=users,dc=example,dc=com').
     */
    baseDn: pulumi.Input<string>;
    /**
     * LDAP bind DN for authentication (e.g., 'cn=admin,dc=example,dc=com').
     */
    bindDn?: pulumi.Input<string>;
    /**
     * Password for the bind DN. Note: stored in Proxmox but not returned by API.
     */
    bindPassword?: pulumi.Input<string>;
    /**
     * Path to CA certificate file for SSL verification.
     */
    caPath?: pulumi.Input<string>;
    /**
     * Enable case-sensitive username matching.
     */
    caseSensitive?: pulumi.Input<boolean>;
    /**
     * Path to client certificate key.
     */
    certKeyPath?: pulumi.Input<string>;
    /**
     * Path to client certificate for SSL authentication.
     */
    certPath?: pulumi.Input<string>;
    /**
     * Description of the realm.
     */
    comment?: pulumi.Input<string>;
    /**
     * Use this realm as the default for login.
     */
    default?: pulumi.Input<boolean>;
    /**
     * LDAP filter for user searches.
     */
    filter?: pulumi.Input<string>;
    /**
     * LDAP objectClasses for groups (comma-separated).
     */
    groupClasses?: pulumi.Input<string>;
    /**
     * LDAP base DN for group searches.
     */
    groupDn?: pulumi.Input<string>;
    /**
     * LDAP filter for group searches.
     */
    groupFilter?: pulumi.Input<string>;
    /**
     * LDAP attribute representing the group name.
     */
    groupNameAttr?: pulumi.Input<string>;
    /**
     * LDAP connection mode (ldap, ldaps, ldap+starttls).
     */
    mode?: pulumi.Input<string>;
    /**
     * LDAP server port. Default: 389 (LDAP) or 636 (LDAPS).
     */
    port?: pulumi.Input<number>;
    /**
     * Realm identifier (e.g., 'example.com').
     */
    realm: pulumi.Input<string>;
    /**
     * Use LDAPS (LDAP over SSL/TLS) instead of plain LDAP.
     *
     * @deprecated Deprecated by Proxmox: use mode instead.
     */
    secure?: pulumi.Input<boolean>;
    /**
     * Primary LDAP server hostname or IP address.
     */
    server1: pulumi.Input<string>;
    /**
     * Fallback LDAP server hostname or IP address.
     */
    server2?: pulumi.Input<string>;
    /**
     * SSL/TLS version (tlsv1, tlsv1*1, tlsv1*2, tlsv1_3).
     */
    sslVersion?: pulumi.Input<string>;
    /**
     * Comma-separated list of attributes to sync (e.g., 'email=mail,firstname=givenName').
     */
    syncAttributes?: pulumi.Input<string>;
    /**
     * Default synchronization options. Format: comma-separated 'key=value' pairs. Valid keys: 'scope' (users/groups/both), 'enable-new' (1/0), 'remove-vanished' (semicolon-separated: entry/acl/properties), 'full' (deprecated), 'purge' (deprecated). Example: 'scope=users,enable-new=1,remove-vanished=entry;acl'.
     */
    syncDefaultsOptions?: pulumi.Input<string>;
    /**
     * LDAP attribute representing the username.
     */
    userAttr?: pulumi.Input<string>;
    /**
     * LDAP objectClasses for users (comma-separated).
     */
    userClasses?: pulumi.Input<string>;
    /**
     * Verify LDAP server SSL certificate.
     */
    verify?: pulumi.Input<boolean>;
}
