// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.muehlbachler.pulumi.proxmoxve.sdn_zone.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetQinqLegacyPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetQinqLegacyPlainArgs Empty = new GetQinqLegacyPlainArgs();

    /**
     * The unique identifier of the SDN zone.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The unique identifier of the SDN zone.
     * 
     */
    public String id() {
        return this.id;
    }

    private GetQinqLegacyPlainArgs() {}

    private GetQinqLegacyPlainArgs(GetQinqLegacyPlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetQinqLegacyPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetQinqLegacyPlainArgs $;

        public Builder() {
            $ = new GetQinqLegacyPlainArgs();
        }

        public Builder(GetQinqLegacyPlainArgs defaults) {
            $ = new GetQinqLegacyPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The unique identifier of the SDN zone.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetQinqLegacyPlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetQinqLegacyPlainArgs", "id");
            }
            return $;
        }
    }

}
