// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ProxmoxVE.Inputs
{

    public sealed class Vm2CdromArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The file ID of the CD-ROM, or `cdrom|none`. Defaults to `none` to leave the CD-ROM empty. Use `cdrom` to connect to the physical drive.
        /// </summary>
        [Input("fileId")]
        public Input<string>? FileId { get; set; }

        public Vm2CdromArgs()
        {
        }
        public static new Vm2CdromArgs Empty => new Vm2CdromArgs();
    }
}
