# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetMappingsCheckResult',
]

@pulumi.output_type
class GetMappingsCheckResult(dict):
    def __init__(__self__, *,
                 mapping_id: _builtins.str,
                 message: _builtins.str,
                 severity: _builtins.str):
        """
        :param _builtins.str mapping_id: The corresponding hardware mapping ID of the node check diagnostic entry.
        :param _builtins.str message: The message of the node check diagnostic entry.
        :param _builtins.str severity: The severity of the node check diagnostic entry.
        """
        pulumi.set(__self__, "mapping_id", mapping_id)
        pulumi.set(__self__, "message", message)
        pulumi.set(__self__, "severity", severity)

    @_builtins.property
    @pulumi.getter(name="mappingId")
    def mapping_id(self) -> _builtins.str:
        """
        The corresponding hardware mapping ID of the node check diagnostic entry.
        """
        return pulumi.get(self, "mapping_id")

    @_builtins.property
    @pulumi.getter
    def message(self) -> _builtins.str:
        """
        The message of the node check diagnostic entry.
        """
        return pulumi.get(self, "message")

    @_builtins.property
    @pulumi.getter
    def severity(self) -> _builtins.str:
        """
        The severity of the node check diagnostic entry.
        """
        return pulumi.get(self, "severity")


