// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package proxmoxve

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-proxmoxve/sdk/v7/go/proxmoxve/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves information about all Replications in Proxmox.
func GetReplications(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetReplicationsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetReplicationsResult
	err := ctx.Invoke("proxmoxve:index/getReplications:getReplications", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getReplications.
type GetReplicationsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// List of Replications.
	Replications []GetReplicationsReplication `pulumi:"replications"`
}

func GetReplicationsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetReplicationsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetReplicationsResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("proxmoxve:index/getReplications:getReplications", nil, GetReplicationsResultOutput{}, options).(GetReplicationsResultOutput), nil
	}).(GetReplicationsResultOutput)
}

// A collection of values returned by getReplications.
type GetReplicationsResultOutput struct{ *pulumi.OutputState }

func (GetReplicationsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetReplicationsResult)(nil)).Elem()
}

func (o GetReplicationsResultOutput) ToGetReplicationsResultOutput() GetReplicationsResultOutput {
	return o
}

func (o GetReplicationsResultOutput) ToGetReplicationsResultOutputWithContext(ctx context.Context) GetReplicationsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetReplicationsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetReplicationsResult) string { return v.Id }).(pulumi.StringOutput)
}

// List of Replications.
func (o GetReplicationsResultOutput) Replications() GetReplicationsReplicationArrayOutput {
	return o.ApplyT(func(v GetReplicationsResult) []GetReplicationsReplication { return v.Replications }).(GetReplicationsReplicationArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetReplicationsResultOutput{})
}
