// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves information about a specific Proxmox VE node.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as proxmoxve from "@muhlba91/pulumi-proxmoxve";
 *
 * const example = proxmoxve.getNode({
 *     nodeName: "pve",
 * });
 * export const dataProxmoxVirtualEnvironmentNode = {
 *     cpuCores: example.then(example => example.cpuCores),
 *     cpuCount: example.then(example => example.cpuCount),
 *     cpuSockets: example.then(example => example.cpuSockets),
 *     cpuModel: example.then(example => example.cpuModel),
 *     memoryTotal: example.then(example => example.memoryTotal),
 *     uptime: example.then(example => example.uptime),
 * };
 * ```
 */
export function getNode(args: GetNodeArgs, opts?: pulumi.InvokeOptions): Promise<GetNodeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("proxmoxve:index/getNode:getNode", {
        "nodeName": args.nodeName,
    }, opts);
}

/**
 * A collection of arguments for invoking getNode.
 */
export interface GetNodeArgs {
    /**
     * The node name
     */
    nodeName: string;
}

/**
 * A collection of values returned by getNode.
 */
export interface GetNodeResult {
    /**
     * The total number of physical CPU cores on the node
     */
    readonly cpuCores: number;
    /**
     * The total number of logical CPUs on the node (sockets * cores * threads)
     */
    readonly cpuCount: number;
    /**
     * The CPU model on the node
     */
    readonly cpuModel: string;
    /**
     * The number of CPU sockets on the node
     */
    readonly cpuSockets: number;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The available memory in bytes on the node
     */
    readonly memoryAvailable: number;
    /**
     * The total memory in bytes on the node
     */
    readonly memoryTotal: number;
    /**
     * The used memory in bytes on the node
     */
    readonly memoryUsed: number;
    /**
     * The node name
     */
    readonly nodeName: string;
    /**
     * The uptime in seconds on the node
     */
    readonly uptime: number;
}
/**
 * Retrieves information about a specific Proxmox VE node.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as proxmoxve from "@muhlba91/pulumi-proxmoxve";
 *
 * const example = proxmoxve.getNode({
 *     nodeName: "pve",
 * });
 * export const dataProxmoxVirtualEnvironmentNode = {
 *     cpuCores: example.then(example => example.cpuCores),
 *     cpuCount: example.then(example => example.cpuCount),
 *     cpuSockets: example.then(example => example.cpuSockets),
 *     cpuModel: example.then(example => example.cpuModel),
 *     memoryTotal: example.then(example => example.memoryTotal),
 *     uptime: example.then(example => example.uptime),
 * };
 * ```
 */
export function getNodeOutput(args: GetNodeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNodeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("proxmoxve:index/getNode:getNode", {
        "nodeName": args.nodeName,
    }, opts);
}

/**
 * A collection of arguments for invoking getNode.
 */
export interface GetNodeOutputArgs {
    /**
     * The node name
     */
    nodeName: pulumi.Input<string>;
}
